import { expect } from 'chai'

import { parseBuildPropString } from '../src/android/prop-reader.js'

describe('Android prop-reader', () => {
  describe('parseBuildPropString', () => {
    it('should parse key=value pairs', () => {
      const content = `ro.build.display.id=BlissOS 16.9.4
ro.build.version.sdk=33
ro.product.cpu.abi=x86_64`

      const props = parseBuildPropString(content)
      expect(props['ro.build.display.id']).to.equal('BlissOS 16.9.4')
      expect(props['ro.build.version.sdk']).to.equal('33')
      expect(props['ro.product.cpu.abi']).to.equal('x86_64')
    })

    it('should skip comments and blank lines', () => {
      const content = `# This is a comment
ro.build.type=userdebug

# Another comment
ro.product.brand=bliss
`

      const props = parseBuildPropString(content)
      expect(Object.keys(props)).to.have.lengthOf(2)
      expect(props['ro.build.type']).to.equal('userdebug')
      expect(props['ro.product.brand']).to.equal('bliss')
    })

    it('should handle values containing equals signs', () => {
      const content = `ro.build.description=bliss_x86_64-userdebug 13 TQ3A.230901.001 eng.user.20240101=test`

      const props = parseBuildPropString(content)
      expect(props['ro.build.description']).to.equal('bliss_x86_64-userdebug 13 TQ3A.230901.001 eng.user.20240101=test')
    })

    it('should handle empty values', () => {
      const content = `ro.build.flavor=
ro.product.device=generic_x86_64`

      const props = parseBuildPropString(content)
      expect(props['ro.build.flavor']).to.equal('')
      expect(props['ro.product.device']).to.equal('generic_x86_64')
    })

    it('should skip lines without equals sign', () => {
      const content = `ro.build.type=userdebug
this line has no equals
ro.product.brand=bliss`

      const props = parseBuildPropString(content)
      expect(Object.keys(props)).to.have.lengthOf(2)
    })

    it('should handle ! style comments', () => {
      const content = `! Java properties comment
ro.build.type=eng`

      const props = parseBuildPropString(content)
      expect(Object.keys(props)).to.have.lengthOf(1)
      expect(props['ro.build.type']).to.equal('eng')
    })

    it('should trim whitespace from keys and values', () => {
      const content = `  ro.build.type  =  userdebug  `

      const props = parseBuildPropString(content)
      expect(props['ro.build.type']).to.equal('userdebug')
    })

    it('should return empty object for empty input', () => {
      const props = parseBuildPropString('')
      expect(Object.keys(props)).to.have.lengthOf(0)
    })

    it('should parse a realistic BlissOS build.prop', () => {
      const content = `# begin build properties
# autogenerated by buildinfo.sh
ro.build.display.id=BlissOS 16.9.4
ro.build.version.incremental=eng.user.20240307.120000
ro.build.version.sdk=33
ro.build.version.release=13
ro.build.type=userdebug
ro.build.flavor=bliss_x86_64-userdebug
ro.product.brand=bliss
ro.product.device=x86_64
ro.product.model=BlissOS
ro.product.cpu.abi=x86_64
ro.product.cpu.abilist=x86_64,x86
ro.product.cpu.abilist32=x86
ro.product.cpu.abilist64=x86_64
ro.boot.dynamic_partitions=true
`

      const props = parseBuildPropString(content)
      expect(props['ro.build.display.id']).to.equal('BlissOS 16.9.4')
      expect(props['ro.build.version.sdk']).to.equal('33')
      expect(props['ro.product.cpu.abi']).to.equal('x86_64')
      expect(props['ro.product.cpu.abilist']).to.equal('x86_64,x86')
      expect(props['ro.product.cpu.abilist32']).to.equal('x86')
      expect(props['ro.product.cpu.abilist64']).to.equal('x86_64')
      expect(props['ro.boot.dynamic_partitions']).to.equal('true')
    })

    it('should parse a realistic ARM64 LineageOS build.prop', () => {
      const content = `ro.build.display.id=lineage_arm64-userdebug 13 TQ3A.230901.001
ro.build.version.sdk=33
ro.build.version.release=13
ro.product.brand=lineage
ro.product.cpu.abi=arm64-v8a
ro.product.cpu.abilist=arm64-v8a,armeabi-v7a,armeabi
ro.product.cpu.abilist32=armeabi-v7a,armeabi
ro.product.cpu.abilist64=arm64-v8a
`

      const props = parseBuildPropString(content)
      expect(props['ro.product.cpu.abi']).to.equal('arm64-v8a')
      expect(props['ro.product.cpu.abilist']).to.equal('arm64-v8a,armeabi-v7a,armeabi')
      expect(props['ro.product.cpu.abilist32']).to.equal('armeabi-v7a,armeabi')
    })
  })
})
