/**
 * Integration tests for the Android backend.
 * Uses synthetic build.prop data and mock filesystem checks
 * to validate the full detection → config → structure pipeline.
 */

import { expect } from 'chai'
import fs from 'node:fs'
import os from 'node:os'
import path from 'node:path'

import { detectAndroidArch } from '../src/android/arch-detect.js'
import { parseBuildPropString } from '../src/android/prop-reader.js'
import {
  generateGrubCfg,
  generateIsolinuxCfg,
  IAndroidIsoConfig,
} from '../src/classes/ovary.d/android/android-iso.js'
import {
  isAndroidBootImage,
} from '../src/classes/ovary.d/android/android-boot-img.js'
import {
  isSparseImage,
} from '../src/classes/ovary.d/android/android-system-img.js'

// Synthetic BlissOS build.prop
const BLISSOS_BUILD_PROP = `# begin build properties
# autogenerated by buildinfo.sh
ro.build.display.id=BlissOS 16.9.4
ro.build.version.incremental=eng.user.20240307.120000
ro.build.version.sdk=33
ro.build.version.release=13
ro.build.version.security_patch=2024-03-01
ro.build.type=userdebug
ro.build.flavor=bliss_x86_64-userdebug
ro.product.brand=bliss
ro.product.device=x86_64
ro.product.model=BlissOS
ro.product.cpu.abi=x86_64
ro.product.cpu.abilist=x86_64,x86
ro.product.cpu.abilist32=x86
ro.product.cpu.abilist64=x86_64
ro.boot.dynamic_partitions=true
`

// Synthetic LineageOS ARM64 build.prop
const LINEAGEOS_BUILD_PROP = `ro.build.display.id=lineage_arm64-userdebug 14 UQ1A.240205.002
ro.build.version.sdk=34
ro.build.version.release=14
ro.build.type=userdebug
ro.build.flavor=lineage_arm64-userdebug
ro.product.brand=lineage
ro.product.device=generic_arm64
ro.product.model=LineageOS
ro.product.cpu.abi=arm64-v8a
ro.product.cpu.abilist=arm64-v8a,armeabi-v7a,armeabi
ro.product.cpu.abilist32=armeabi-v7a,armeabi
ro.product.cpu.abilist64=arm64-v8a
`

// Synthetic RISC-V Cuttlefish build.prop
const RISCV_BUILD_PROP = `ro.build.display.id=aosp_riscv64-userdebug 15 AP31.240617.009
ro.build.version.sdk=35
ro.build.version.release=15
ro.build.type=userdebug
ro.product.brand=aosp
ro.product.device=vsoc_riscv64
ro.product.model=Cuttlefish riscv64
ro.product.cpu.abi=riscv64
ro.product.cpu.abilist=riscv64
ro.product.cpu.abilist32=
ro.product.cpu.abilist64=riscv64
`

describe('Android Integration', () => {
  describe('Full detection pipeline — BlissOS x86_64', () => {
    const props = parseBuildPropString(BLISSOS_BUILD_PROP)
    const arch = detectAndroidArch(props)

    it('should detect x86_64 primary ABI', () => {
      expect(arch.primaryAbi).to.equal('x86_64')
    })

    it('should detect x86 secondary ABI (multilib)', () => {
      expect(arch.secondaryAbi).to.equal('x86')
      expect(arch.isMultilib).to.be.true
    })

    it('should identify as BlissOS', () => {
      expect(props['ro.product.brand']).to.equal('bliss')
      expect(props['ro.build.display.id']).to.include('BlissOS')
    })

    it('should detect Android 13 / SDK 33', () => {
      expect(props['ro.build.version.release']).to.equal('13')
      expect(props['ro.build.version.sdk']).to.equal('33')
    })

    it('should detect dynamic partitions', () => {
      expect(props['ro.boot.dynamic_partitions']).to.equal('true')
    })
  })

  describe('Full detection pipeline — LineageOS ARM64', () => {
    const props = parseBuildPropString(LINEAGEOS_BUILD_PROP)
    const arch = detectAndroidArch(props)

    it('should detect arm64-v8a primary ABI', () => {
      expect(arch.primaryAbi).to.equal('arm64-v8a')
    })

    it('should detect armeabi-v7a secondary ABI', () => {
      expect(arch.secondaryAbi).to.equal('armeabi-v7a')
      expect(arch.isMultilib).to.be.true
    })

    it('should map to aarch64 kernel arch', () => {
      expect(arch.kernelArch).to.equal('aarch64')
    })
  })

  describe('Full detection pipeline — RISC-V Cuttlefish', () => {
    const props = parseBuildPropString(RISCV_BUILD_PROP)
    const arch = detectAndroidArch(props)

    it('should detect riscv64 primary ABI', () => {
      expect(arch.primaryAbi).to.equal('riscv64')
    })

    it('should not have secondary ABI', () => {
      expect(arch.secondaryAbi).to.be.null
      expect(arch.isMultilib).to.be.false
    })

    it('should be 64-bit', () => {
      expect(arch.is64Bit).to.be.true
    })

    it('should detect Android 15 / SDK 35', () => {
      expect(props['ro.build.version.release']).to.equal('15')
      expect(props['ro.build.version.sdk']).to.equal('35')
    })
  })

  describe('GRUB config generation', () => {
    it('should generate valid GRUB config for x86_64', () => {
      const config: IAndroidIsoConfig = {
        arch: 'x86_64',
        compression: 'zstd',
        extraCmdline: '',
        includeData: false,
        initrdPath: '/boot/initrd.img',
        kernelPath: '/boot/kernel',
        outputPath: '/tmp/test.iso',
        systemRoot: '/system',
        verbose: false,
        volid: 'BlissOS',
      }

      const grubCfg = generateGrubCfg(config)

      expect(grubCfg).to.include('menuentry')
      expect(grubCfg).to.include('linux /kernel')
      expect(grubCfg).to.include('initrd /initrd.img')
      expect(grubCfg).to.include('androidboot.selinux=permissive')
      expect(grubCfg).to.include('set timeout=10')
      expect(grubCfg).to.include('Debug mode')
      expect(grubCfg).to.include('Boot from local disk')
    })
  })

  describe('Isolinux config generation', () => {
    it('should generate valid isolinux config', () => {
      const config: IAndroidIsoConfig = {
        arch: 'x86',
        compression: 'gzip',
        extraCmdline: '',
        includeData: false,
        initrdPath: '/boot/initrd.img',
        kernelPath: '/boot/bzImage',
        outputPath: '/tmp/test.iso',
        systemRoot: '/system',
        verbose: false,
        volid: 'Android-x86',
      }

      const isolinuxCfg = generateIsolinuxCfg(config)

      expect(isolinuxCfg).to.include('default vesamenu.c32')
      expect(isolinuxCfg).to.include('kernel /bzImage')
      expect(isolinuxCfg).to.include('initrd=/initrd.img')
      expect(isolinuxCfg).to.include('androidboot.selinux=permissive')
      expect(isolinuxCfg).to.include('label android')
      expect(isolinuxCfg).to.include('label debug')
    })
  })

  describe('Boot image magic detection', () => {
    it('should reject non-boot-image files', () => {
      // Create a temp file with random content
      const tmpFile = path.join(os.tmpdir(), 'eggs-test-not-boot.img')
      fs.writeFileSync(tmpFile, 'This is not a boot image')
      expect(isAndroidBootImage(tmpFile)).to.be.false
      fs.unlinkSync(tmpFile)
    })

    it('should detect valid Android boot image magic', () => {
      // Create a temp file with ANDROID! magic
      const tmpFile = path.join(os.tmpdir(), 'eggs-test-boot.img')
      const buf = Buffer.alloc(4096, 0)
      buf.write('ANDROID!', 0, 'ascii')
      fs.writeFileSync(tmpFile, buf)
      expect(isAndroidBootImage(tmpFile)).to.be.true
      fs.unlinkSync(tmpFile)
    })

    it('should return false for non-existent files', () => {
      expect(isAndroidBootImage('/nonexistent/boot.img')).to.be.false
    })
  })

  describe('Sparse image magic detection', () => {
    it('should reject non-sparse files', () => {
      const tmpFile = path.join(os.tmpdir(), 'eggs-test-not-sparse.img')
      fs.writeFileSync(tmpFile, 'Not a sparse image')
      expect(isSparseImage(tmpFile)).to.be.false
      fs.unlinkSync(tmpFile)
    })

    it('should detect valid sparse image magic', () => {
      // Android sparse image magic: 0xed26ff3a (little-endian)
      const tmpFile = path.join(os.tmpdir(), 'eggs-test-sparse.img')
      const buf = Buffer.alloc(4096, 0)
      buf[0] = 0xed
      buf[1] = 0x26
      buf[2] = 0xff
      buf[3] = 0x3a
      fs.writeFileSync(tmpFile, buf)
      expect(isSparseImage(tmpFile)).to.be.true
      fs.unlinkSync(tmpFile)
    })

    it('should return false for non-existent files', () => {
      expect(isSparseImage('/nonexistent/system.img')).to.be.false
    })
  })
})
