#!/bin/bash
source /etc/os-release
sudo calamares -d > calamares.${ID}.log.txt 2>&1
scp calamares.${ID}.log.txt artisan@192.168.1.2:/home/artisan/${ID}
scp -r /etc/calamares/* artisan@192.168.1.2:/home/artisan/${ID}
