#!/bin/bash
#
# apt install ttyrec ttygif gifcicle
#
# https://misc.flogisoft.com/bash/tip_colors_and_formatting
#

# colors variables
DEFAULT="\e[39m"
BLACK="\e[30m"
RED="\e[31m"
GREEN="\e[32m"
YELLOW="\e[33m"
BLUE="\e[34"
MAGENTA="\e[35"
CYAN="\e[36"

BGDEFAULT="\e[49m"
BGRED="\e[41m"
BGGREEN="\e[42m"
BGYELLOW="\e[43m"
BGBLUE="\e[44m"
BGMAGENTA="\e[45m"
BGCYAN="\e[46m"

# font variables
BOLD="\033[1m"
NORMAL="\033[0m"

#
#
#
function main() {
    title
    if [ -z "$fname" ]; then
        echo "No argument supplied! You need to give a record name"
        exit
    fi

    check_file_exist
    if_want_to_record
    record
}


#
# function check_file_exist() {
#
function check_file_exist() {
    title
    if [ -f "$gifname" ]; then
        echo "File ${gifname} exist, change name or delete it!"
        exit
    fi
}

function if_want_to_record() {
    title

    echo -e "${BGRED}You will enter in record mode.${BGDEFAULT}"
    echo -e "Give same examples, remember to use # for comments."
    echo -e "Your session will be recorded on: ${BGBLUE}${gifname}${BGDEFAULT}"
    echo -e "Remember: use ${BGGREEN}Ctrl-D${BGDEFAULT} to finish your record"
    echo ""
    read -p "$(echo -e "Enter ${BGGREEN}Y${BGDEFAULT} to continue, or ${BGRED}N${BGDEFAULT} to abort: ")" response

    case "$response" in
        [yYsS]) 
            record
            ;;
        *)
            echo "You choose to abort your session"
            ;;
    esac
}

#
#
#
function record() {
    export WINDOWID=$(xdotool getwindowfocus)
    title
    echo "You are recording..."
    ttyrec ${fname}
    echo "Giferize ${fname}"
    ttygif ${fname}
    echo "Optimize ${fname}.gif"
    gifsicle -i tty.gif --optimize=3 --colors 16 -o ${gifname}
    echo "Removing stuff..."
    rm tty.gif
    rm ${fname}
    echo "Your session is recorded in ${gifname}"
}

#
#
#
function title(){
    clear
    echo -e "${BGBLUE}g4gif${BGDEFAULT} - terminal session recorder"
}

fname=$1
gifname=$fname.gif
main