#!/bin/bash
#
# apt install ttyrec ttygif gifsicle -y
#
# https://misc.flogisoft.com/bash/tip_colors_and_formatting
#

# colors variables
DEFAULT="\e[39m"
BLACK="\e[30m"
RED="\e[31m"
GREEN="\e[32m"
YELLOW="\e[33m"
BLUE="\e[34"
MAGENTA="\e[35"
CYAN="\e[36"

BGDEFAULT="\e[49m"
BGRED="\e[41m"
BGGREEN="\e[42m"
BGYELLOW="\e[43m"
BGBLUE="\e[44m"
BGMAGENTA="\e[45m"
BGCYAN="\e[46m"

# font variables
BOLD="\033[1m"
NORMAL="\033[0m"

#
#
#
function main() {
    cmd=`xdotool getactivewindow`
    export WINDOWID=$(cmd)

    DEFAULT=$PS1

    title
    if [ -z "$fname" ]; then
        echo "No argument supplied! You need to give a record name"
        exit
    fi

    check_file_exist
    record
    #export PS1=${DEFAULT}
    #export PS1

}


#
# function check_file_exist() {
#
function check_file_exist() {
    title
    if [ -f "$gifname" ]; then
        echo "File ${gifname} exist, change name or delete it!"
        exit
    fi
}

function record() {
    title

    echo -e "${BGRED}You will enter in record mode.${BGDEFAULT}"
    echo -e "Give same examples, remember to use # for comments."
    echo -e "Your session will be recorded on: ${BGBLUE}${gifname}${BGDEFAULT}"
    echo -e "Remember: use ${BGGREEN}Ctrl-D${BGDEFAULT} to finish your record"
    echo ""
    read -p "$(echo -e "Enter ${BGGREEN}Y${BGDEFAULT} to continue, or ${BGRED}N${BGDEFAULT} to abort: ")" response

    case "$response" in
        [yYsS]) 
            recording
            giferizing
            optimizing
            cleaning
            ;;
        *)
            echo "You choose to abort your session"
            ;;
    esac
}

#
# salva su un file ${fname}
#
function recording() {
    title
    echo "You are recording..."
    export PS1='\[\e[1;32m\][me@home:~ ]\$\[\e[0m\]'
    ttyrec ${fname}
}    

#
# va a leggere ${fname} sul terminale WINDOWID
# crea tty.gif
#
function giferizing(){
    cmd=`xdotool getactivewindow`
    WINDOWID=${cmd}
    echo "Giferizing ${fname}"
    ttygif ${fname}
}

function optimizing() {
    echo "Optimizing ${fname}.gif"
    gifsicle -i tty.gif --optimize=3 --colors 16 -o ${gifname}
}

function cleaning() {
    echo "cleaning stuff..."
    rm tty.gif
    rm ${fname}
    echo "Your session is recorded in ${gifname}"
}


#
#
#
function title(){
    clear
    echo -e "${BGBLUE}g4gif${BGDEFAULT} - terminal session recorder"
}

fname=$1
gifname=$fname.gif
main