# /etc/penguins-eggs.d/installer/machineid.conf statico per coa
---
systemd: true
dbus: true
symlink: true
entropy-copy: true
entropy-files:
  - /var/lib/urandom/random-seed
  - /var/lib/systemd/random-seed
