# /etc/oa-tools.d/installer/modules/shellprocess@removelink.conf
i18n:
     name: "Removing penguins-eggs live artifacts..."

dontChroot: false
timeout: 30
script:
    # Rimuove l'agente dinamico e l'autostart (che impedisce la ricreazione dell'icona al riavvio)
    - "-rm -f /usr/local/bin/oa-trust-desktop"
    - "-rm -f /etc/xdg/autostart/trust-installer.desktop"
    
    # Rimuove il launcher dal menu delle applicazioni del sistema installato
    - "-rm -f /usr/share/applications/install-system.desktop"
    
    # Rimuove la regola sudoers temporanea
    - "-rm -f /etc/sudoers.d/00-live"
