#!/bin/bash
sudo cp scripts/eggs.bash /etc/bash_completion.d/eggs
sudo cp addons/eggs/adapt/bin/adapt /usr/local/bin/adapt
sudo cp assets/eggs.png /usr/share/icons/
DESKTOP_DIR=$(xdg-user-dir DESKTOP)
cp addons/eggs/adapt/applications/eggs-adapt.desktop ${DESKTOP_DIR}
cp assets/penguins-eggs.desktop ${DESKTOP_DIR}
