app: penguins-eggs
version: latest

# --- Metadati Hub ---
icon: https://raw.githubusercontent.com/pieroproietti/penguins-eggs/main/appimage/penguins-eggs.png
website: https://github.com/pieroproietti/penguins-eggs
github: pieroproietti/penguins-eggs
license: GPL-3.0
categories:
  - System
  - Utility
  - ConsoleOnly
description: CLI tool for Linux remastering and live system creation

# --- 1. BASE SYSTEM (Debian Bookworm) ---
ingredients:
  dist: bookworm
  sources:
    - deb http://deb.debian.org/debian bookworm main contrib non-free
  packages:
    # NOTA: Non mettiamo 'nodejs' qui, perché Bookworm ha solo la v18.
    # Lo installiamo manualmente nello script sotto.
    
    # --- I MUSCOLI (Tools di sistema) ---
    - xorriso
    - squashfs-tools
    - mtools
    - dosfstools
    - rsync
    - parted
    - gdisk
    - cryptsetup
    - lvm2
    - curl
    - git
    - jq
    - sshfs
    - e2fsprogs
    - util-linux
    - coreutils
    - procps

# --- 2. COSTRUZIONE E INIEZIONE ---
script:
  # --- A. INSTALLAZIONE NODEJS 22 (Manuale) ---
  - echo "Installazione Node.js 22 LTS..."
  - # Scarichiamo il tarball ufficiale Linux x64
  - wget -q https://nodejs.org/dist/v22.11.0/node-v22.11.0-linux-x64.tar.xz
  - # Lo estraiamo direttamente in usr/ (simulando un'installazione di sistema dentro l'AppImage)
  - tar -xJf node-v22.11.0-linux-x64.tar.xz --strip-components=1 -C usr/
  - rm node-v22.11.0-linux-x64.tar.xz
  - node --version # Verifica che sia la v22

  # --- B. SCARICA PENGUINS-EGGS ---
  - echo "Scaricamento pacchetto eggs..."
  - wget -q https://github.com/pieroproietti/penguins-eggs/releases/latest/download/penguins-eggs_current_amd64.deb -O eggs.deb
  - dpkg -x eggs.deb .

  # --- C. INIEZIONE BOOTLOADERS (da Debian Trixie/Sid) ---
  - echo "Recupero bootloaders da Debian Trixie..."
  - mkdir -p usr/lib/penguins-eggs/bootloaders
  - mkdir -p temp_trixie
  - cd temp_trixie

  # Download dei pacchetti "donor" (Controlla periodicamente i link se cambiano versione)
  - wget -q http://ftp.debian.org/debian/pool/main/s/syslinux/syslinux-common_6.04~git20190206.bf6db5b4+dfsg1-3_all.deb
  - wget -q http://ftp.debian.org/debian/pool/main/s/syslinux/syslinux_6.04~git20190206.bf6db5b4+dfsg1-3_amd64.deb
  - wget -q http://ftp.debian.org/debian/pool/main/s/syslinux/isolinux_6.04~git20190206.bf6db5b4+dfsg1-3_all.deb
  - wget -q http://ftp.debian.org/debian/pool/main/s/syslinux/pxelinux_6.04~git20190206.bf6db5b4+dfsg1-3_all.deb
  - wget -q http://ftp.debian.org/debian/pool/main/g/grub2/grub-efi-amd64-bin_2.12-5_amd64.deb
  - wget -q http://ftp.debian.org/debian/pool/main/g/grub2/grub-pc-bin_2.12-5_amd64.deb
  - wget -q http://ftp.debian.org/debian/pool/main/i/ipxe/ipxe_1.21.1+git20220113.f6c4074-1_all.deb
  # Estrazione
  - for f in *.deb; do dpkg -x "$f" .; done

  # --- D. POSIZIONAMENTO ASSET ---
  - cd .. # Ritorna alla root AppDir

  # Syslinux / Isolinux / Pxelinux
  - cp -r temp_trixie/usr/lib/syslinux/* usr/lib/penguins-eggs/bootloaders/
  - cp -r temp_trixie/usr/lib/ISOLINUX/* usr/lib/penguins-eggs/bootloaders/ 2>/dev/null || true
  - cp -r temp_trixie/usr/lib/PXELINUX/* usr/lib/penguins-eggs/bootloaders/ 2>/dev/null || true

  # Grub
  - mkdir -p usr/lib/penguins-eggs/bootloaders/grub
  - cp -r temp_trixie/usr/lib/grub/* usr/lib/penguins-eggs/bootloaders/grub/

  # iPXE
  - mkdir -p usr/lib/penguins-eggs/bootloaders/ipxe
  - cp -r temp_trixie/usr/lib/ipxe/* usr/lib/penguins-eggs/bootloaders/ipxe/

  # --- E. PULIZIA E FINITURA ---
  - rm -rf temp_trixie eggs.deb
  
  # Metadata
  - cp usr/share/applications/penguins-eggs.desktop .
  - cp usr/share/icons/hicolor/256x256/apps/penguins-eggs.png .
  
  # Link simbolico opzionale per rassicurare eventuali script che cercano 'node'
  - ln -s node usr/bin/nodejs 2>/dev/null || true