#!/bin/bash

# This script will REMOVE penguins-eggs on your system
# from /usr/lib/penguins-eggs/
# it is intended for development purposes only

clear
echo "removing penguins-eggs on /usr/lib/penguins-eggs/"

sudo rm -f /usr/share/bash-completion/completions/eggs.bash
sudo rm -f /usr/local/bin/g4*
sudo rm -f /usr/share/icons/eggs.png
sudo rm -f /usr/share/man/man1/eggs.1.gz
sudo rm -rf /usr/lib/penguins-eggs/
sudo rm -f /usr/bin/eggs
sudo rm -f /etc/penguins-eggs.d
sudo rm -f /var/local/yolk

# removing stuffs from desktop
DESKTOP_DIR=$(xdg-user-dir DESKTOP)
rm -f "${DESKTOP_DIR}"/eggs-adapt.desktop
rm -f "${DESKTOP_DIR}"/penguins-eggs.desktop

# removing /home/eggs
sudo rm -rf /home/eggs
