/**
 * integration/audit/grant-license.ts
 *
 * License compliance scanning for penguins-recovery ISOs using anchore/grant.
 * Works with SBOMs generated by syft-generate.ts.
 *
 * Adapted from penguins-eggs-audit/plugins/sbom/grant-license.
 * https://github.com/anchore/grant
 *
 * Usage (after generating an SBOM with syft-generate.ts):
 *
 *   const grant = new RecoveryGrant(execFn)
 *   if (await grant.isAvailable()) {
 *     const result = await grant.check('/path/to/recovery.sbom.json')
 *     console.log('License check passed:', result.passed)
 *   }
 */

import fs from 'node:fs'

type ExecFn = (cmd: string, opts?: { capture?: boolean; echo?: boolean }) => Promise<{ code: number; data: string; error?: string }>

export interface RecoveryGrantConfig {
  /** Path to a .grant.yaml policy file. If omitted, uses the default policy. */
  policyFile?: string
  /** Throw if denied licenses are found. Default: true. */
  failOnDeny?: boolean
}

export interface RecoveryLicenseResult {
  passed: boolean
  output: string
  target: string
}

// Recovery ISOs bundle many packages. This policy allows common open-source
// licenses and denies copyleft licenses that may restrict redistribution.
const DEFAULT_RECOVERY_POLICY = `# grant license policy for penguins-recovery ISOs
# See: https://github.com/anchore/grant
rules:
  - pattern: "GPL-3.0"
    mode: deny
  - pattern: "AGPL-3.0"
    mode: deny
  - pattern: "MIT"
    mode: allow
  - pattern: "Apache-2.0"
    mode: allow
  - pattern: "BSD-2-Clause"
    mode: allow
  - pattern: "BSD-3-Clause"
    mode: allow
  - pattern: "ISC"
    mode: allow
  - pattern: "GPL-2.0"
    mode: allow
`

export class RecoveryGrant {
  private exec: ExecFn

  constructor(exec: ExecFn) {
    this.exec = exec
  }

  async isAvailable(): Promise<boolean> {
    const result = await this.exec('command -v grant', { capture: true })
    return result.code === 0
  }

  /**
   * Check license compliance of an SBOM or target path against a grant policy.
   * target is typically the SBOM file produced by RecoverySyft.generate().
   */
  async check(target: string, config: RecoveryGrantConfig = {}): Promise<RecoveryLicenseResult> {
    const policyFlag = config.policyFile ? `--config ${config.policyFile}` : ''

    const result = await this.exec(
      `grant check ${policyFlag} ${target}`,
      { capture: true, echo: true }
    )

    const passed = result.code === 0

    if (!passed && config.failOnDeny !== false) {
      throw new Error(`License policy violation in recovery ISO:\n${result.data}`)
    }

    return { passed, output: result.data, target }
  }

  /**
   * List all licenses found in a target (SBOM, container image, or directory).
   */
  async list(target: string): Promise<string> {
    const result = await this.exec(`grant list ${target}`, { capture: true })
    return result.data
  }

  /**
   * Write a default .grant.yaml policy file if one does not already exist.
   */
  initPolicy(outputPath = '.grant.yaml'): void {
    if (fs.existsSync(outputPath)) return
    fs.writeFileSync(outputPath, DEFAULT_RECOVERY_POLICY)
  }
}
