#!/bin/bash
# Rescapp Update-grub run script
# Copyright (C) 2012,2013,2014,2015,2016,2017,2018,2019,2020 Adrian Gibanel Lopez
#
# Rescapp is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# Rescapp is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Rescapp.  If not, see <http://www.gnu.org/licenses/>.

source ${RESCAPP_LIB_FILE}
set -x
set -v

# MAIN PROGRAM

UEFIORDER_OK_STR="The UEFI Boot order, was updated OK! :)"
UEFIORDER_KO_STR="The UEFI Boot order, update went wrong! :("
UEFIORDER_RUNNING_STR="Updating UEFI Boot order."
UEFI_ORDER_NOT_FOUND="UEFI order was not set."

UEFI_DESIRED_ORDER=$(rtux_Choose_UEFI_Boot_Order_Update)
if [ ! "x${UEFI_DESIRED_ORDER}" == "x" ] ; then
  if rtux_Run_Show_Progress "${UEFIORDER_RUNNING_STR}" rtux_UEFI_Boot_Order_Update ${UEFI_DESIRED_ORDER};
  then
    rtux_Message_Success ${UEFIORDER_OK_STR}
  else
    rtux_Message_Failure ${UEFIORDER_KO_STR}
  fi
else
  rtux_Message_Warning ${UEFI_ORDER_NOT_FOUND}
  rtux_Message_Failure ${UEFIORDER_KO_STR}
fi


#
