#!/bin/bash
# Rescapp gparted run script
# Copyright (C) 2012,2013,2014,2015,2016,2017,2018,2019,2020 Adrian Gibanel Lopez
#
# Rescapp is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# Rescapp is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Rescapp.  If not, see <http://www.gnu.org/licenses/>.

source ${RESCAPP_LIB_FILE}
set -x
set -v

GPARTED_OK_STR="Gparted was successfully started in the background."
GPARTED_KO_STR="Rescapp was unable to start Gparted, is it installed?"

GPARTED_FULL_PATH="$(which gparted)"
if [ -x "${GPARTED_FULL_PATH}" ] ; then
    "${GPARTED_FULL_PATH}" &
    rtux_Message_Success ${GPARTED_OK_STR}
else
    rtux_Message_Failure ${GPARTED_KO_STR}
fi

