/**
 *
 */
export function automirror(versionId = ''): string {
    let text = ''
    text += `#!/usr/bin/env python3\n`
    text += `# Copyright (C) 2018 Simon Quigley <tsimonq2@ubuntu.com>\n`
    text += `#\n`
    text += `# This program is free software: you can redistribute it and/or modify\n`
    text += `# it under the terms of the GNU General Public License as published by\n`
    text += `# the Free Software Foundation, either version 3 of the License, or\n`
    text += `# (at your option) any later version.\n`
    text += `#\n`
    text += `# This program is distributed in the hope that it will be useful,\n`
    text += `# but WITHOUT ANY WARRANTY; without even the implied warranty of\n`
    text += `# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the\n`
    text += `# GNU General Public License for more details.\n`
    text += `#\n`
    text += `# You should have received a copy of the GNU General Public License\n`
    text += `# along with this program. If not, see <http://www.gnu.org/licenses/>.\n`
    text += `\n`
    text += `import json\n`
    text += `import libcalamares\n`
    text += `from time import strftime\n`
    text += `import urllib.request\n`
    text += `from urllib.error import HTTPError\n`
    text += `from urllib.error import URLError\n`
    text += `import socket\n`
    text += `import logging\n`
    text += `from lsb_release import get_distro_information\n`
    text += `\n`
    text += `global sources\n`
    text += `sources = """# Automatically generated by Calamares on DATE.\n`
    text += `\n`

    /**
     * LINUXMINT 20, 19.3
     */
    if (versionId === 'ulyana') {
        text += `deb http://packages.linuxmint.com ulyana main upstream import backport #id:linuxmint_main\n`
        text += `\n`
    } else if (versionId === 'tricia') {
        text += `deb http://packages.linuxmint.com tricia main upstream import backport #id:linuxmint_main\n`
        text += `\n`
    }
    text += `deb URL/ubuntu/ CODENAME main restricted universe multiverse\n`
    text += `deb URL/ubuntu/ CODENAME-updates main restricted universe multiverse\n`
    text += `deb URL/ubuntu/ CODENAME-backports main restricted universe multiverse\n`
    text += `\n`
    text += `deb http://security.ubuntu.com/ubuntu/ CODENAME-security main restricted universe multiverse\n`
    text += `deb http://archive.canonical.com/ubuntu CODENAME partner"""\n`

    text += `\n`
    text += `SUBDOMAINS_BY_COUNTRY_CODE = {"US": "us.",\n`
    text += `                              "AU": "au.",\n`
    text += `                              "SE": "no.",\n`
    text += `                              "NO": "no.",\n`
    text += `                              "NZ": "nz.",\n`
    text += `                              "NL": "nl.",\n`
    text += `                              "KR": "kr.",\n`
    text += `                              "DE": "de.",\n`
    text += `                              "GE": "ge.",\n`
    text += `                              "PF": "pf.",\n`
    text += `                              "CZ": "cz.",\n`
    text += `                              "HR": "hr."}\n`
    text += `\n`
    text += `def getcountrycode():\n`
    text += `    """\n`
    text += `    Return the two-letter country code or an empty string.\n`
    text += `\n`
    text += `    Tries to determine the country code based on the public IP address,\n`
    text += `    if the device is connected to the Internet. Otherwise it returns\n`
    text += `    an empty string.\n`
    text += `    """\n`
    text += `    if libcalamares.globalstorage.value("hasInternet"):\n`
    text += `        geoipurl = libcalamares.job.configuration["geoip"]["url"]\n`
    text += `        try:\n`
    text += `            with urllib.request.urlopen(geoipurl, timeout=75) as http_response:\n`
    text += `                localedata = json.loads(http_response.read().decode())\n`
    text += `        except HTTPError as http_error:\n`
    text += `            logging.http_error("Data not retrieved because %s - URL: %s",\n`
    text += `                               http_error, geoipurl)\n`
    text += `        except URLError as url_error:\n`
    text += `            if isinstance(url_error.reason, socket.timeout):\n`
    text += `                logging.error("Socket timed out - URL %s", geoipurl)\n`
    text += `            else:\n`
    text += `                logging.error("Non-timeout protocol error.")\n`
    text += `        else:\n`
    text += `            logging.info("Country successfully determined.")\n`
    text += `            return localedata["country"]\n`
    text += `    else:\n`
    text += `        return ""\n`
    text += `def get_subdomain_by_country(countrycode):\n`
    text += `    """Return the subdomain for the given countrycode\n`
    text += `    or an empty string.\n`
    text += `    """\n`
    text += `    if countrycode in SUBDOMAINS_BY_COUNTRY_CODE.keys():\n`
    text += `        return SUBDOMAINS_BY_COUNTRY_CODE[countrycode]\n`
    text += `    else:\n`
    text += `        return ""\n`
    text += `\n`
    text += `def getcodename():\n`
    text += `    """Return the codename of the distribution, similar to lsb_release -cs"""\n`
    if (versionId === 'ulyana') {
        text += `    return "focal"\n`
    } else if (versionId === 'tricia') {
        text += `    return "bionic"\n`
    } else {
        text += `    return get_distro_information()["CODENAME"]\n`
    }
    text += `\n`
    text += `def changesources(subdomain):\n`
    text += `    """Replace the placeholders and then create the sources.list"""\n`
    text += `    distro = libcalamares.job.configuration["distribution"]\n`
    text += `    url = "http://{}{}".format(subdomain,\n`
    text += `libcalamares.job.configuration["baseUrl"])\n`
    text += `\n`
    text += `    global sources\n`
    text += `    sources = sources.replace("DISTRIBUTION", distro)\n`
    text += `    sources = sources.replace("CODENAME", getcodename())\n`
    text += `    sources = sources.replace("URL", url)\n`
    text += `    sources = sources.replace("DATE", strftime("%Y-%m-%d"))\n`
    text += `\n`
    text += `    filepath = libcalamares.globalstorage.value("rootMountPoint")\n`
    if ((versionId === 'ulyana') || (versionId === 'tricia')) {
        text += `    # Linux mint ${versionId}\n`
        text += `    filepath += "/etc/apt/sources.list.d/official-package-repositories.list"\n`
    } else {
        text += `    filepath += "/etc/apt/sources.list"\n`
    }
    text += `    with open(filepath, "r+") as sourcesfile:\n`
    text += `        sourcesfile.seek(0)\n`
    text += `        sourcesfile.write(sources)\n`
    text += `        sourcesfile.truncate()\n`
    text += `\n`
    text += `def run():\n`
    text += `    """Autoselect a mirror and create the sources.list file."""\n`
    text += `    countrycode = getcountrycode()\n`
    text += `    subdomain = get_subdomain_by_country(countrycode)\n`
    text += `\n`
    text += `    changesources(subdomain)\n`

    return text
}
