#!/bin/bash

# check if we are on opensuse
if ! grep -q -E '^ID="?opensuse' /etc/os-release; then
    echo "This script is only for opensuse-slowroll"
    exit 1
fi

# check if we are root
if [ "$EUID" -eq 0 ]; then
  echo "Please run as normal user"
  exit
fi

echo "Building package..."
/usr/bin/rpmbuild -bb --define "dist .opensuse" ./penguins-eggs-deps.spec
cp $HOME/rpmbuild/RPMS/noarch/penguins-eggs-deps-*.opensuse.noarch.rpm .
