/**
 * plugins/sbom/grant-license/grant-license.ts
 *
 * License compliance scanning for eggs ISO artifacts using anchore/grant.
 * Works with SBOMs generated by syft-generate.
 *
 * https://github.com/anchore/grant
 */

import fs from 'node:fs'
import path from 'node:path'

type ExecFn = (cmd: string, opts?: { capture?: boolean; echo?: boolean }) => Promise<{ code: number; data: string; error?: string }>

export interface GrantConfig {
  policyFile?: string   // path to .grant.yaml; defaults to repo root
  failOnDeny?: boolean  // throw if denied licenses found (default: true)
}

export interface LicenseCheckResult {
  passed: boolean
  output: string
  target: string
}

const DEFAULT_POLICY = `# grant license policy — generated by penguins-eggs-audit
# See: https://github.com/anchore/grant
rules:
  - pattern: "GPL-3.0"
    mode: deny
  - pattern: "AGPL-3.0"
    mode: deny
  - pattern: "MIT"
    mode: allow
  - pattern: "Apache-2.0"
    mode: allow
  - pattern: "BSD-2-Clause"
    mode: allow
  - pattern: "BSD-3-Clause"
    mode: allow
`

export class GrantLicense {
  private exec: ExecFn

  constructor(exec: ExecFn) {
    this.exec = exec
  }

  /**
   * Check whether the grant binary is on PATH.
   */
  async isAvailable(): Promise<boolean> {
    const result = await this.exec('command -v grant', { capture: true })
    return result.code === 0
  }

  /**
   * Check license compliance of an SBOM or target path against a grant policy.
   */
  async check(target: string, config: GrantConfig = {}): Promise<LicenseCheckResult> {
    const policyFlag = config.policyFile ? `--config ${config.policyFile}` : ''

    const result = await this.exec(
      `grant check ${policyFlag} ${target}`,
      { capture: true, echo: true }
    )

    const passed = result.code === 0

    if (!passed && config.failOnDeny !== false) {
      throw new Error(`License policy violation:\n${result.data}`)
    }

    return { passed, output: result.data, target }
  }

  /**
   * List all licenses found in a target (SBOM, container image, or directory).
   */
  async list(target: string): Promise<string> {
    const result = await this.exec(`grant list ${target}`, { capture: true })
    return result.data
  }

  /**
   * Write a default .grant.yaml policy file if one does not already exist.
   */
  initPolicy(outputPath = '.grant.yaml'): void {
    if (fs.existsSync(outputPath)) return
    fs.writeFileSync(outputPath, DEFAULT_POLICY)
  }
}
