# reven — generic x86_64 ChromiumOS board (sebanc/chromiumos-stage3 original)
# Suitable for: amd64 container base images, amd64 stage3 tarballs
BOARD=reven
ARCH=amd64
CHOST=x86_64-cros-linux-gnu
BOOTSTRAP_ARCH=x86_64
BOOTSTRAP_URL=https://geo.mirror.pkgbuild.com/iso/latest/archlinux-bootstrap-x86_64.tar.zst
BOOTSTRAP_STRIP=1
PROFILE_PATH=default/linux/amd64/10.0/chromeos
GCC_USE_FLAGS="-multilib"
EXTRA_PACKAGES=""
