Vagrant.configure("2") do |config|
  # Usiamo 'arch' come nome interno univoco
  config.vm.define "arch" do |node|
    node.vm.box = "generic/arch"
    node.vm.hostname = "naked-arch"

    node.vm.provider "libvirt" do |lv|
      lv.memory = 4096
      lv.cpus = 4
      lv.cpu_mode = "host-passthrough"
    end

    # Montiamo l'intera root del progetto
    node.vm.synced_folder "../..", "/vagrant", 
      type: "9p", 
      disabled: false, 
      mount_options: ["version=9p2000.L", "trans=virtio", "access=any", "uid=1000", "gid=1000"]

    # Provisioning
    node.vm.provision "shell", inline: <<-SHELL
      set -eux
      modprobe overlay
      modprobe loop
      modprobe squashfs
      pacman-key --init
      pacman-key --populate archlinux
      pacman -Sy archlinux-keyring --noconfirm
      pacman -Su --noconfirm
      pacman -S --noconfirm base-devel go git make xorriso squashfs-tools bash-completion dosfstools mtools
    SHELL
  end
end