Vagrant.configure("2") do |config|
  # Nome macchina univoco per la matrice
  config.vm.define "arch" do |node|
    node.vm.box = "generic/arch"
    node.vm.hostname = "naked-arch"

    node.vm.provider "libvirt" do |lv|
      lv.memory = 4096
      lv.cpus = 4
      lv.cpu_mode = "host-passthrough"
    end

    # Mount 9p per la condivisione del workspace
    node.vm.synced_folder "../..", "/vagrant", 
      type: "9p", 
      disabled: false, 
      mount_options: ["version=9p2000.L", "trans=virtio", "access=any", "uid=1000", "gid=1000"]

    # Provisioning blindato
    node.vm.provision "shell", inline: <<-SHELL
      set -eux
      
      # Abilita sudo senza password
      echo "vagrant ALL=(ALL) NOPASSWD: ALL" > /etc/sudoers.d/vagrant
      chmod 0440 /etc/sudoers.d/vagrant

      # Moduli necessari
      modprobe overlay
      modprobe loop
      modprobe squashfs
      
      # Inizializzazione pacman
      pacman-key --init
      pacman-key --populate archlinux
      pacman -Sy archlinux-keyring --noconfirm
      pacman -Su --noconfirm
      
      # Installazione dipendenze
      pacman -S --noconfirm base-devel go git make xorriso squashfs-tools bash-completion dosfstools mtools
    SHELL
  end
end
