package cmd

import (
	"fmt"
	"os"
	"path/filepath"

	"github.com/spf13/cobra"
)

// grub40Cmd represents the 'coa tools grub40' command
var grub40Cmd = &cobra.Command{
	Use:   "grub40 [path/to/iso]",
	Short: "Generate GRUB configuration to boot an ISO via loopback",
	Long:  `Calculates the absolute path of the ISO, detects its size, and prints the configuration block to be inserted into /etc/grub.d/40_custom.`,
	Args:  cobra.ExactArgs(1),
	Run: func(cmd *cobra.Command, args []string) {
		isoPath := args[0]

		// Ottiene il percorso assoluto a prova di errore
		absPath, err := filepath.Abs(isoPath)
		if err != nil {
			fmt.Fprintf(os.Stderr, "Error calculating absolute path: %v\n", err)
			os.Exit(1)
		}

		// Legge i metadati del file per ottenere la dimensione e verificare che esista
		info, err := os.Stat(absPath)
		if err != nil {
			fmt.Fprintf(os.Stderr, "Error: cannot access file (are you sure it exists?): %v\n", err)
			os.Exit(1)
		}

		// Converte la dimensione in MB o GB per renderla leggibile
		sizeBytes := info.Size()
		var sizeStr string
		if sizeBytes >= 1024*1024*1024 {
			sizeStr = fmt.Sprintf("%.2f GB", float64(sizeBytes)/(1024*1024*1024))
		} else {
			sizeStr = fmt.Sprintf("%.2f MB", float64(sizeBytes)/(1024*1024))
		}

		// Estrae solo il nome del file per il menu di GRUB
		isoName := filepath.Base(absPath)

		// Il template del blocco GRUB in inglese
		grubTemplate := `
# Copy this block into your /etc/grub.d/40_custom file
# and remember to run 'sudo update-grub' after saving.
#
# Note: This boot entry uses Debian's live-boot parameters.
# It is completely universal: you can paste it into the GRUB of ANY host OS,
# and it will successfully boot ANY ISO generated by oa-tools,
# regardless of the Linux distribution contained inside the image.
#
# File: %s
# Detected size: %s

menuentry "oa-tools: %s" --class isoboot {
    insmod part_gpt
    insmod part_msdos
    insmod ext2
    insmod iso9660
    insmod loopback

    set isofile="%s"

    search --no-floppy --set=root --file $isofile
    loopback loop $isofile

    linux (loop)/live/vmlinuz boot=live components rootwait findiso=$isofile
    initrd (loop)/live/initrd.img
}
`
		// Stampa il risultato a video passando i parametri
		fmt.Printf(grubTemplate, isoName, sizeStr, isoName, absPath)
	},
}

func init() {
	toolsCmd.AddCommand(grub40Cmd)
}
