package cmd

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/spf13/cobra"
)

// grub40Cmd represents the 'coa tools grub40' command
var grub40Cmd = &cobra.Command{
	Use:   "grub40 [path/to/iso]",
	Short: "Generate GRUB configuration to boot an ISO via loopback",
	Long:  `Calculates the exact path of the ISO for GRUB (handling BTRFS subvolumes and separate mount points), detects its size, and prints the configuration block.`,
	Args:  cobra.ExactArgs(1),
	Run: func(cmd *cobra.Command, args []string) {
		isoPath := args[0]

		// 1. Ottiene il percorso assoluto dal punto di vista del sistema host
		absPath, err := filepath.Abs(isoPath)
		if err != nil {
			fmt.Fprintf(os.Stderr, "Error calculating absolute path: %v\n", err)
			os.Exit(1)
		}

		// 2. Verifica l'esistenza del file e ne legge la dimensione
		info, err := os.Stat(absPath)
		if err != nil {
			fmt.Fprintf(os.Stderr, "Error: cannot access file (are you sure it exists?): %v\n", err)
			os.Exit(1)
		}

		sizeBytes := info.Size()
		var sizeStr string
		if sizeBytes >= 1024*1024*1024 {
			sizeStr = fmt.Sprintf("%.2f GB", float64(sizeBytes)/(1024*1024*1024))
		} else {
			sizeStr = fmt.Sprintf("%.2f MB", float64(sizeBytes)/(1024*1024))
		}

		isoName := filepath.Base(absPath)

		// 3. Calcola il percorso reale che GRUB si aspetta (gestione BTRFS e Mount Point)
		grubPath := calculateGrubPath(absPath)

		// Il template del blocco GRUB universale in inglese
		grubTemplate := `
# Copy this block into your /etc/grub.d/40_custom file
# and remember to run 'sudo update-grub' after saving.
#
# Note: This boot entry uses Debian's live-boot parameters.
# It is completely universal: you can paste it into the GRUB of ANY host OS,
# and it will successfully boot ANY ISO generated by oa-tools,
# regardless of the Linux distribution contained inside the image.
#
# File: %s
# Detected size: %s

menuentry "oa-tools: %s" --class isoboot {
    insmod part_gpt
    insmod part_msdos
    insmod ext2
    insmod btrfs
    insmod iso9660
    insmod loopback

    set isofile="%s"

    search --no-floppy --set=root --file $isofile
    loopback loop $isofile

    linux (loop)/live/vmlinuz boot=live components rootwait findiso=$isofile
    initrd (loop)/live/initrd.img
}
`
		// Stampa il risultato a video passandogli il percorso corretto per GRUB
		fmt.Printf(grubTemplate, isoName, sizeStr, isoName, grubPath)
	},
}

// Logica intelligente per mappare il percorso reale per GRUB analizzando i mount point dell'host
func calculateGrubPath(absPath string) string {
	data, err := os.ReadFile("/proc/mounts")
	if err != nil {
		return absPath // Fallback al percorso assoluto standard in caso di errore
	}

	type Mount struct {
		Point   string
		FSType  string
		Options []string
	}

	var mounts []Mount
	lines := strings.Split(string(data), "\n")
	for _, line := range lines {
		fields := strings.Fields(line)
		if len(fields) < 4 {
			continue
		}
		mounts = append(mounts, Mount{
			Point:   fields[1],
			FSType:  fields[2],
			Options: strings.Split(fields[3], ","),
		})
	}

	// Troviamo il mount point più specifico (più lungo) che contiene il nostro file
	var bestMatch Mount
	bestMatchLen := -1

	for _, m := range mounts {
		if m.Point == "/" {
			if bestMatchLen < 0 {
				bestMatch = m
				bestMatchLen = 0
			}
		} else if strings.HasPrefix(absPath, m.Point) {
			// Protezione per evitare falsi positivi (es: /home/eggs vs /home-alt)
			if len(absPath) == len(m.Point) || absPath[len(m.Point)] == '/' {
				if len(m.Point) > bestMatchLen {
					bestMatch = m
					bestMatchLen = len(m.Point)
				}
			}
		}
	}

	if bestMatchLen == -1 {
		return absPath
	}

	// Calcoliamo il percorso relativo rispetto al suo punto di montaggio
	relPath := absPath
	if bestMatch.Point != "/" {
		relPath = strings.TrimPrefix(absPath, bestMatch.Point)
	}
	if !strings.HasPrefix(relPath, "/") {
		relPath = "/" + relPath
	}

	// Se il filesystem è BTRFS, dobbiamo estrarre il subvolume e metterlo come prefisso
	if bestMatch.FSType == "btrfs" {
		subvol := ""
		for _, opt := range bestMatch.Options {
			if strings.HasPrefix(opt, "subvol=") {
				subvol = strings.TrimPrefix(opt, "subvol=")
				break
			}
		}
		// Se c'è un subvolume valido (diverso dalla radice btrfs "/"), lo combiniamo
		if subvol != "" && subvol != "/" {
			subvol = strings.TrimSuffix(subvol, "/")
			return subvol + relPath
		}
	}

	// Per Ext4 con partizioni separate (es: /home), relPath è già perfetto così (es: /eggs/iso...)
	return relPath
}

func init() {
	toolsCmd.AddCommand(grub40Cmd)
}
