#!/bin/sh

# Created at: 2025-03-20_1126
# By: penguins_eggs v. 10.0.60
# ==> Perri's Brewery edition <== 

# NOTE: cdrom, dev, live, media, mnt, proc, run, sys and tmp
#       need just a mkdir in /home/eggs/.mnt/filesystem.squashfs
# host: minimal user: dummy

#############################################################
# /bin is a symbolic link to /usr/bin in the system
# we need just to recreate it
# ln -s /home/eggs/.mnt/filesystem.squashfs/usr/bin /home/eggs/.mnt/filesystem.squashfs/usr/bin
# but we don't know if the destination exist, and I'm too lazy today. So, for now: 
# ---------------------------------------------------------
cp -r /bin /home/eggs/.mnt/filesystem.squashfs
# ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

#############################################################
# /boot is copied
cp -r /boot /home/eggs/.mnt/filesystem.squashfs
# ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

#############################################################
# ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

#############################################################
# /dev is a directory need to be present, no mount
# ---------------------------------------------------------
mkdir /home/eggs/.mnt/filesystem.squashfs/dev -p
# mount -o bind /dev /home/eggs/.mnt/filesystem.squashfs/dev
# ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

#############################################################
# /etc is copied
cp -r /etc /home/eggs/.mnt/filesystem.squashfs
# ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

#############################################################
# /home is a directory need to be present, no mount
# ---------------------------------------------------------
mkdir /home/eggs/.mnt/filesystem.squashfs/home -p
# mount -o bind /home /home/eggs/.mnt/filesystem.squashfs/home
# ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

#############################################################
# /initrd.img is a symbolic link to /boot/initrd.img-6.1.0-30-amd64 in the system
# we need just to recreate it
# ln -s /home/eggs/.mnt/filesystem.squashfs/boot/initrd.img-6.1.0-30-amd64 /home/eggs/.mnt/filesystem.squashfs/boot/initrd.img-6.1.0-30-amd64
# but we don't know if the destination exist, and I'm too lazy today. So, for now: 
# ---------------------------------------------------------
cp -r /initrd.img /home/eggs/.mnt/filesystem.squashfs
# ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

#############################################################
# /initrd.img.old is a symbolic link to /boot/initrd.img-6.1.0-30-amd64 in the system
# we need just to recreate it
# ln -s /home/eggs/.mnt/filesystem.squashfs/boot/initrd.img-6.1.0-30-amd64 /home/eggs/.mnt/filesystem.squashfs/boot/initrd.img-6.1.0-30-amd64
# but we don't know if the destination exist, and I'm too lazy today. So, for now: 
# ---------------------------------------------------------
cp -r /initrd.img.old /home/eggs/.mnt/filesystem.squashfs
# ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

#############################################################
# /lib is a symbolic link to /usr/lib in the system
# we need just to recreate it
# ln -s /home/eggs/.mnt/filesystem.squashfs/usr/lib /home/eggs/.mnt/filesystem.squashfs/usr/lib
# but we don't know if the destination exist, and I'm too lazy today. So, for now: 
# ---------------------------------------------------------
cp -r /lib /home/eggs/.mnt/filesystem.squashfs
# ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

#############################################################
# /lib64 is a symbolic link to /usr/lib64 in the system
# we need just to recreate it
# ln -s /home/eggs/.mnt/filesystem.squashfs/usr/lib64 /home/eggs/.mnt/filesystem.squashfs/usr/lib64
# but we don't know if the destination exist, and I'm too lazy today. So, for now: 
# ---------------------------------------------------------
cp -r /lib64 /home/eggs/.mnt/filesystem.squashfs
# ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

#############################################################
# /media is a directory need to be present, no mount
# ---------------------------------------------------------
mkdir /home/eggs/.mnt/filesystem.squashfs/media -p
# mount -o bind /media /home/eggs/.mnt/filesystem.squashfs/media
# ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

#############################################################
# /mnt is a directory need to be present, no mount
# ---------------------------------------------------------
mkdir /home/eggs/.mnt/filesystem.squashfs/mnt -p
# mount -o bind /mnt /home/eggs/.mnt/filesystem.squashfs/mnt
# ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

#############################################################
# /opt is a directory need to be present, mount ro
# ---------------------------------------------------------
mkdir /home/eggs/.mnt/filesystem.squashfs/opt -p
mount --bind --make-slave /opt /home/eggs/.mnt/filesystem.squashfs/opt
mount -o remount,bind,ro /home/eggs/.mnt/filesystem.squashfs/opt
# ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

#############################################################
# /proc is a directory need to be present, no mount
# ---------------------------------------------------------
mkdir /home/eggs/.mnt/filesystem.squashfs/proc -p
# mount -o bind /proc /home/eggs/.mnt/filesystem.squashfs/proc
# ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

#############################################################
# /root is a directory need to be present, mount ro
# ---------------------------------------------------------
mkdir /home/eggs/.mnt/filesystem.squashfs/root -p
mount --bind --make-slave /root /home/eggs/.mnt/filesystem.squashfs/root
mount -o remount,bind,ro /home/eggs/.mnt/filesystem.squashfs/root
# ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

#############################################################
# /run is a directory need to be present, no mount
# ---------------------------------------------------------
mkdir /home/eggs/.mnt/filesystem.squashfs/run -p
# mount -o bind /run /home/eggs/.mnt/filesystem.squashfs/run
# ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

#############################################################
# /sbin is a symbolic link to /usr/sbin in the system
# we need just to recreate it
# ln -s /home/eggs/.mnt/filesystem.squashfs/usr/sbin /home/eggs/.mnt/filesystem.squashfs/usr/sbin
# but we don't know if the destination exist, and I'm too lazy today. So, for now: 
# ---------------------------------------------------------
cp -r /sbin /home/eggs/.mnt/filesystem.squashfs
# ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

#############################################################
# /srv is a directory need to be present, mount ro
# ---------------------------------------------------------
mkdir /home/eggs/.mnt/filesystem.squashfs/srv -p
mount --bind --make-slave /srv /home/eggs/.mnt/filesystem.squashfs/srv
mount -o remount,bind,ro /home/eggs/.mnt/filesystem.squashfs/srv
# ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

#############################################################
# /sys is a directory need to be present, no mount
# ---------------------------------------------------------
mkdir /home/eggs/.mnt/filesystem.squashfs/sys -p
# mount -o bind /sys /home/eggs/.mnt/filesystem.squashfs/sys
# ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

#############################################################
# /tmp is a directory need to be present, no mount
# ---------------------------------------------------------
mkdir /home/eggs/.mnt/filesystem.squashfs/tmp -p
# mount -o bind /tmp /home/eggs/.mnt/filesystem.squashfs/tmp
# ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

#############################################################
# /usr is a directory need to be present, and rw
# ---------------------------------------------------------
# create mountpoint lower
mkdir /home/eggs/.overlay/lowerdir/usr -p
# first: mount /usr rw in /home/eggs/.overlay/lowerdir/usr
mount --bind --make-slave /usr /home/eggs/.overlay/lowerdir/usr
# now remount it ro
mount -o remount,bind,ro /home/eggs/.overlay/lowerdir/usr

# second: create mountpoint upper, work and /home/eggs/.mnt/filesystem.squashfs and mount usr
mkdir /home/eggs/.overlay/upperdir/usr -p
mkdir /home/eggs/.overlay/workdir/usr -p
mkdir /home/eggs/.mnt/filesystem.squashfs/usr -p

# thirth: mount /usr rw in /home/eggs/.mnt/filesystem.squashfs
mount -t overlay overlay -o lowerdir=/home/eggs/.overlay/lowerdir/usr,upperdir=/home/eggs/.overlay/upperdir/usr,workdir=/home/eggs/.overlay/workdir/usr /home/eggs/.mnt/filesystem.squashfs/usr
# ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

#############################################################
# /var is a directory need to be present, and rw
# ---------------------------------------------------------
# create mountpoint lower
mkdir /home/eggs/.overlay/lowerdir/var -p
# first: mount /var rw in /home/eggs/.overlay/lowerdir/var
mount --bind --make-slave /var /home/eggs/.overlay/lowerdir/var
# now remount it ro
mount -o remount,bind,ro /home/eggs/.overlay/lowerdir/var

# second: create mountpoint upper, work and /home/eggs/.mnt/filesystem.squashfs and mount var
mkdir /home/eggs/.overlay/upperdir/var -p
mkdir /home/eggs/.overlay/workdir/var -p
mkdir /home/eggs/.mnt/filesystem.squashfs/var -p

# thirth: mount /var rw in /home/eggs/.mnt/filesystem.squashfs
mount -t overlay overlay -o lowerdir=/home/eggs/.overlay/lowerdir/var,upperdir=/home/eggs/.overlay/upperdir/var,workdir=/home/eggs/.overlay/workdir/var /home/eggs/.mnt/filesystem.squashfs/var
# ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

#############################################################
# /vmlinuz is a symbolic link to /boot/vmlinuz-6.1.0-30-amd64 in the system
# we need just to recreate it
# ln -s /home/eggs/.mnt/filesystem.squashfs/boot/vmlinuz-6.1.0-30-amd64 /home/eggs/.mnt/filesystem.squashfs/boot/vmlinuz-6.1.0-30-amd64
# but we don't know if the destination exist, and I'm too lazy today. So, for now: 
# ---------------------------------------------------------
cp -r /vmlinuz /home/eggs/.mnt/filesystem.squashfs
# ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

#############################################################
# /vmlinuz.old is a symbolic link to /boot/vmlinuz-6.1.0-30-amd64 in the system
# we need just to recreate it
# ln -s /home/eggs/.mnt/filesystem.squashfs/boot/vmlinuz-6.1.0-30-amd64 /home/eggs/.mnt/filesystem.squashfs/boot/vmlinuz-6.1.0-30-amd64
# but we don't know if the destination exist, and I'm too lazy today. So, for now: 
# ---------------------------------------------------------
cp -r /vmlinuz.old /home/eggs/.mnt/filesystem.squashfs
# ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
