#!/bin/sh

# Created at: 2025-03-21_1147
# By: penguins_eggs v. 10.0.60
# ==> Perri's Brewery edition <== 

# NOTE: cdrom, dev, live, media, mnt, proc, run, sys and tmp
#       need just a mkdir in /home/eggs/.mnt/filesystem.squashfs
# host: colibri user: artisan

#############################################################
# /bin is a symbolic link to /
cp -r /bin /home/eggs/.mnt/filesystem.squashfs
#

#############################################################
# /boot is a directory
# /boot is copied
cp -r /boot /home/eggs/.mnt/filesystem.squashfs
#

#############################################################
# /ci is a directory
#

#############################################################
# /dev is a directory
# /dev just created
mkdir /home/eggs/.mnt/filesystem.squashfs/dev -p
#

#############################################################
# /etc is a directory
# /etc is copied
cp -r /etc /home/eggs/.mnt/filesystem.squashfs
#

#############################################################
# /home is a directory
# /home just created
mkdir /home/eggs/.mnt/filesystem.squashfs/home -p
#

#############################################################
# /lib is a symbolic link to /usr/bin
cp -r /lib /home/eggs/.mnt/filesystem.squashfs
#

#############################################################
# /lib64 is a symbolic link to /usr/lib
cp -r /lib64 /home/eggs/.mnt/filesystem.squashfs
#

#############################################################
# /lost+found is a directory
#

#############################################################
# /mnt is a directory
# /mnt just created
mkdir /home/eggs/.mnt/filesystem.squashfs/mnt -p
#

#############################################################
# /opt is a directory
# /opt merged (ro)
mkdir /home/eggs/.mnt/filesystem.squashfs/opt -p
mount --bind --make-slave /opt /home/eggs/.mnt/filesystem.squashfs/opt
mount -o remount,bind,ro /home/eggs/.mnt/filesystem.squashfs/opt
#

#############################################################
# /proc is a directory
# /proc just created
mkdir /home/eggs/.mnt/filesystem.squashfs/proc -p
#

#############################################################
# /root is a directory
# /root merged (ro)
mkdir /home/eggs/.mnt/filesystem.squashfs/root -p
mount --bind --make-slave /root /home/eggs/.mnt/filesystem.squashfs/root
mount -o remount,bind,ro /home/eggs/.mnt/filesystem.squashfs/root
#

#############################################################
# /run is a directory
# /run just created
mkdir /home/eggs/.mnt/filesystem.squashfs/run -p
#

#############################################################
# /sbin is a symbolic link to /usr/lib
cp -r /sbin /home/eggs/.mnt/filesystem.squashfs
#

#############################################################
# /srv is a directory
# /srv merged (ro)
mkdir /home/eggs/.mnt/filesystem.squashfs/srv -p
mount --bind --make-slave /srv /home/eggs/.mnt/filesystem.squashfs/srv
mount -o remount,bind,ro /home/eggs/.mnt/filesystem.squashfs/srv
#

#############################################################
# /sys is a directory
# /sys just created
mkdir /home/eggs/.mnt/filesystem.squashfs/sys -p
#

#############################################################
# /tmp is a directory
# /tmp just created
mkdir /home/eggs/.mnt/filesystem.squashfs/tmp -p
#

#############################################################
# /usr is a directory
# /usr mergedAndOverlay (rw)

# create mountpoint lower
mkdir /home/eggs/.overlay/lowerdir/usr -p
# first: mount /usr rw in /home/eggs/.overlay/lowerdir/usr
mount --bind --make-slave /usr /home/eggs/.overlay/lowerdir/usr
# now remount it ro
mount -o remount,bind,ro /home/eggs/.overlay/lowerdir/usr

# second: create mountpoint upper, work and /home/eggs/.mnt/filesystem.squashfs and mount usr
mkdir /home/eggs/.overlay/upperdir/usr -p
mkdir /home/eggs/.overlay/workdir/usr -p
mkdir /home/eggs/.mnt/filesystem.squashfs/usr -p

# thirth: mount /usr rw in /home/eggs/.mnt/filesystem.squashfs
mount -t overlay overlay -o lowerdir=/home/eggs/.overlay/lowerdir/usr,upperdir=/home/eggs/.overlay/upperdir/usr,workdir=/home/eggs/.overlay/workdir/usr /home/eggs/.mnt/filesystem.squashfs/usr
#

#############################################################
# /var is a directory
# /var mergedAndOverlay (rw)

# create mountpoint lower
mkdir /home/eggs/.overlay/lowerdir/var -p
# first: mount /var rw in /home/eggs/.overlay/lowerdir/var
mount --bind --make-slave /var /home/eggs/.overlay/lowerdir/var
# now remount it ro
mount -o remount,bind,ro /home/eggs/.overlay/lowerdir/var

# second: create mountpoint upper, work and /home/eggs/.mnt/filesystem.squashfs and mount var
mkdir /home/eggs/.overlay/upperdir/var -p
mkdir /home/eggs/.overlay/workdir/var -p
mkdir /home/eggs/.mnt/filesystem.squashfs/var -p

# thirth: mount /var rw in /home/eggs/.mnt/filesystem.squashfs
mount -t overlay overlay -o lowerdir=/home/eggs/.overlay/lowerdir/var,upperdir=/home/eggs/.overlay/upperdir/var,workdir=/home/eggs/.overlay/workdir/var /home/eggs/.mnt/filesystem.squashfs/var
#
