/**
 * ./src/krill/classes/sequence.d/android_fstab.ts
 * penguins-eggs — Android backend
 * license: MIT
 *
 * Generates Android-specific fstab for the installed system.
 *
 * Android uses a different fstab format than standard Linux:
 *   - Located at /vendor/etc/fstab.{hardware} or /system/etc/fstab.{hardware}
 *   - Format: <device> <mount_point> <type> <mount_flags> <fs_mgr_flags>
 *   - fs_mgr_flags include: wait, verify, avb, logical, etc.
 *
 * For x86 installs, we also generate a standard /etc/fstab for the
 * Linux init stage (GRUB → initrd → mount root → switch_root).
 */

import fs from 'node:fs'
import path from 'node:path'

import Utils from '../../../classes/utils.js'
import Sequence from '../../classes/sequence.js'

/**
 * Generate Android fstab for the installed system.
 * Creates both the Android-format fstab and a Linux /etc/fstab.
 */
export async function androidFstab(this: Sequence, installDevice: string): Promise<void> {
  const installTarget = this.installTarget

  // Determine hardware name from build.prop or device
  const hardware = getHardwareName()

  // Generate Android-format fstab
  await generateAndroidFstab(installTarget, installDevice, hardware, this)

  // Generate standard Linux /etc/fstab (needed for initrd mount)
  await generateLinuxFstab(installTarget, installDevice, this)
}

/**
 * Generate the Android-format fstab at /vendor/etc/fstab.{hardware}
 *
 * Format per line:
 *   <src> <mnt_point> <type> <mnt_flags and options> <fs_mgr_flags>
 */
async function generateAndroidFstab(
  installTarget: string,
  installDevice: string,
  hardware: string,
  seq: Sequence
): Promise<void> {
  const vendorEtc = path.join(installTarget, 'vendor', 'etc')
  if (!fs.existsSync(vendorEtc)) {
    fs.mkdirSync(vendorEtc, { recursive: true })
  }

  const fstabPath = path.join(vendorEtc, `fstab.${hardware}`)

  let text = `# Android fstab — generated by penguins-eggs\n`
  text += `# <src>                                      <mnt_point>  <type>  <mnt_flags and options>                  <fs_mgr_flags>\n`

  // /system partition
  if (seq.devices.root.name !== 'none') {
    const uuid = Utils.uuid(seq.devices.root.name)
    text += `UUID=${uuid}  /system  ext4  ro,barrier=1  wait,avb=vbmeta_system\n`
  }

  // /vendor partition
  if (seq.devices.data.name !== 'none' && seq.devices.data.mountPoint === '/vendor') {
    const uuid = Utils.uuid(seq.devices.data.name)
    text += `UUID=${uuid}  /vendor  ext4  ro,barrier=1  wait,avb=vbmeta_vendor\n`
  }

  // /data partition
  if (seq.devices.swap.name !== 'none' && seq.devices.swap.mountPoint === '/data') {
    const uuid = Utils.uuid(seq.devices.swap.name)
    text += `UUID=${uuid}  /data  ext4  noatime,nosuid,nodev,barrier=1,data=ordered,nomblk_io_submit  wait,check,formattable,fileencryption=aes-256-xts:aes-256-cts:v2+inlinecrypt_optimized,keydirectory=/metadata/vold/metadata_encryption,quota,reservedsize=128M\n`
  }

  // /cache (directory inside /data on modern Android, but some builds want it)
  text += `/dev/null  /cache  tmpfs  nosuid,nodev,noexec  defaults\n`

  // /misc (if present)
  text += `/dev/null  /misc  emmc  defaults  defaults\n`

  Utils.write(fstabPath, text)
  Utils.warning(`created ${fstabPath}`)

  // Also place a copy at /system/etc/ for compatibility
  const systemEtc = path.join(installTarget, 'system', 'etc')
  if (fs.existsSync(systemEtc)) {
    const systemFstab = path.join(systemEtc, `fstab.${hardware}`)
    Utils.write(systemFstab, text)
  }
}

/**
 * Generate standard Linux /etc/fstab for the initrd mount stage.
 * This is used by the Linux init (before Android init takes over).
 */
async function generateLinuxFstab(
  installTarget: string,
  installDevice: string,
  seq: Sequence
): Promise<void> {
  const etcDir = path.join(installTarget, 'etc')
  if (!fs.existsSync(etcDir)) {
    fs.mkdirSync(etcDir, { recursive: true })
  }

  const fstabPath = path.join(etcDir, 'fstab')

  let text = `# /etc/fstab — generated by penguins-eggs (Android install)\n`
  text += `# <device>  <mount>  <type>  <options>  <dump>  <pass>\n`

  // Root = /system
  if (seq.devices.root.name !== 'none') {
    text += `UUID=${Utils.uuid(seq.devices.root.name)}  /system  ext4  ro,noatime  0  1\n`
  }

  // Vendor
  if (seq.devices.data.name !== 'none' && seq.devices.data.mountPoint === '/vendor') {
    text += `UUID=${Utils.uuid(seq.devices.data.name)}  /vendor  ext4  ro,noatime  0  2\n`
  }

  // Data
  if (seq.devices.swap.name !== 'none' && seq.devices.swap.mountPoint === '/data') {
    text += `UUID=${Utils.uuid(seq.devices.swap.name)}  /data  ext4  noatime,nosuid,nodev  0  2\n`
  }

  // EFI
  if (seq.devices.efi.name !== 'none') {
    text += `UUID=${Utils.uuid(seq.devices.efi.name)}  /boot/efi  vfat  defaults  0  2\n`
  }

  // Boot (BIOS)
  if (seq.devices.boot.name !== 'none') {
    text += `UUID=${Utils.uuid(seq.devices.boot.name)}  /boot  ext4  defaults  0  2\n`
  }

  // No swap — Android doesn't use swap
  text += `# Android does not use swap\n`

  // tmpfs for Android
  text += `tmpfs  /tmp  tmpfs  nosuid,nodev  0  0\n`

  Utils.write(fstabPath, text)
  Utils.warning(`created ${fstabPath}`)
}

/**
 * Get the hardware name for fstab.{hardware}.
 * Android uses this to find the right fstab at boot.
 */
function getHardwareName(): string {
  // Try reading from build.prop
  try {
    const buildPropPaths = ['/system/build.prop', '/vendor/build.prop']
    for (const bp of buildPropPaths) {
      if (fs.existsSync(bp)) {
        const data = fs.readFileSync(bp, 'utf8')
        for (const line of data.split('\n')) {
          if (line.startsWith('ro.hardware=')) {
            return line.split('=')[1].trim()
          }
        }
      }
    }
  } catch { /* ignore */ }

  // Try /proc/cmdline
  try {
    if (fs.existsSync('/proc/cmdline')) {
      const cmdline = fs.readFileSync('/proc/cmdline', 'utf8')
      const match = cmdline.match(/androidboot\.hardware=(\w+)/)
      if (match) return match[1]
    }
  } catch { /* ignore */ }

  // Default for x86
  return 'android_x86_64'
}
