/**
 * ./src/krill/classes/sequence.d/android_bootloader.ts
 * penguins-eggs — Android backend
 * license: MIT
 *
 * Installs and configures the bootloader for an Android system.
 *
 * For x86/x86_64: GRUB2 with Android-specific kernel parameters
 * For ARM64: U-Boot configuration (extlinux.conf)
 * For RISC-V: OpenSBI + U-Boot/EDK2
 *
 * Android boot differs from standard Linux:
 *   - Kernel params include androidboot.* flags
 *   - SELinux mode must be specified
 *   - SRC= and DATA= point to partition locations
 *   - Hardware name is passed via androidboot.hardware=
 */

import fs from 'node:fs'
import path from 'node:path'

import { readBuildProp } from '../../../android/prop-reader.js'
import Utils from '../../../classes/utils.js'
import { exec } from '../../../lib/utils.js'
import Sequence from '../../classes/sequence.js'

/**
 * Install and configure the bootloader for Android.
 */
export async function androidBootloader(this: Sequence): Promise<void> {
  const arch: string = process.arch

  if (arch === 'x64' || arch === 'ia32') {
    await installGrubAndroid.call(this)
  } else if (arch === 'arm64') {
    await installUbootAndroid.call(this)
  } else if (arch === 'riscv64') {
    await installGrubAndroid.call(this) // RISC-V uses GRUB via UEFI
  } else {
    Utils.warning(`Unsupported architecture for Android bootloader: ${arch}`)
  }
}

/**
 * Install GRUB for Android x86/x86_64/RISC-V.
 */
async function installGrubAndroid(this: Sequence): Promise<void> {
  const installTarget = this.installTarget

  // Install GRUB to the target
  if (this.efi) {
    let target = 'x86_64-efi'
    let extraArgs = ''

    if (process.arch === 'riscv64') {
      target = 'riscv64-efi'
      extraArgs = '--removable'
    }

    const cmd = `chroot ${installTarget} grub-install --target=${target} --efi-directory=/boot/efi --bootloader-id=android --recheck ${extraArgs}`
    await exec(cmd, this.echo)
  } else {
    const cmd = `chroot ${installTarget} grub-install --target=i386-pc ${this.partitions.installationDevice}`
    await exec(cmd, this.echo)
  }

  // Generate Android-specific GRUB config
  await generateAndroidGrubCfg.call(this)
}

/**
 * Generate GRUB configuration with Android-specific kernel parameters.
 */
async function generateAndroidGrubCfg(this: Sequence): Promise<void> {
  const installTarget = this.installTarget

  // Find the kernel and initrd in the installed system
  const kernelName = findInstalledKernel(installTarget)
  const initrdName = findInstalledInitrd(installTarget)

  if (!kernelName || !initrdName) {
    Utils.warning('kernel or initrd not found, falling back to grub-mkconfig')
    await exec(`chroot ${installTarget} grub-mkconfig -o /boot/grub/grub.cfg`, this.echo)
    return
  }

  // Get Android-specific parameters
  const hardware = readBuildProp('ro.hardware') || 'android_x86_64'
  const displayId = readBuildProp('ro.build.display.id') || 'Android'
  const androidVersion = readBuildProp('ro.build.version.release') || ''

  const systemUuid = Utils.uuid(this.devices.root.name)
  const dataUuid = this.devices.swap.name !== 'none'
    ? Utils.uuid(this.devices.swap.name)
    : ''

  // Android kernel command line
  const androidCmdline = [
    `root=UUID=${systemUuid}`,
    `androidboot.selinux=permissive`,
    `androidboot.hardware=${hardware}`,
    `SRC=/system`,
    dataUuid ? `DATA=UUID=${dataUuid}` : '',
  ].filter(Boolean).join(' ')

  const title = `${displayId}${androidVersion ? ` (Android ${androidVersion})` : ''}`

  // Write GRUB config
  const grubDir = path.join(installTarget, 'boot', 'grub')
  if (!fs.existsSync(grubDir)) {
    fs.mkdirSync(grubDir, { recursive: true })
  }

  const grubCfg = `# GRUB configuration for ${title}
# Generated by penguins-eggs Android installer

set default=0
set timeout=10
set gfxmode=auto

insmod all_video
insmod gfxterm

terminal_output gfxterm

menuentry "${title}" --class android {
    linux /boot/${kernelName} ${androidCmdline} quiet
    initrd /boot/${initrdName}
}

menuentry "${title} (Debug mode)" --class android {
    linux /boot/${kernelName} ${androidCmdline} DEBUG=2
    initrd /boot/${initrdName}
}

menuentry "${title} (Vulkan)" --class android {
    linux /boot/${kernelName} ${androidCmdline} VULKAN=1 quiet
    initrd /boot/${initrdName}
}

menuentry "Boot from local disk" {
    set root=(hd0)
    chainloader +1
}
`

  const grubCfgPath = path.join(grubDir, 'grub.cfg')
  fs.writeFileSync(grubCfgPath, grubCfg)
  Utils.warning(`created ${grubCfgPath}`)

  // Also write /etc/default/grub for future grub-mkconfig runs
  const defaultGrub = path.join(installTarget, 'etc', 'default')
  if (!fs.existsSync(defaultGrub)) {
    fs.mkdirSync(defaultGrub, { recursive: true })
  }

  const defaultGrubContent = `# /etc/default/grub — Android (penguins-eggs)
GRUB_DEFAULT=0
GRUB_TIMEOUT=10
GRUB_CMDLINE_LINUX_DEFAULT="${androidCmdline} quiet"
GRUB_CMDLINE_LINUX=""
GRUB_TERMINAL_OUTPUT="gfxterm"
`
  fs.writeFileSync(path.join(defaultGrub, 'grub'), defaultGrubContent)
}

/**
 * Install U-Boot configuration for Android ARM64.
 * Uses extlinux.conf format (compatible with U-Boot distro boot).
 */
async function installUbootAndroid(this: Sequence): Promise<void> {
  const installTarget = this.installTarget

  const kernelName = findInstalledKernel(installTarget)
  const initrdName = findInstalledInitrd(installTarget)
  const dtbDir = path.join(installTarget, 'boot', 'dtbs')

  const hardware = readBuildProp('ro.hardware') || 'android_arm64'
  const displayId = readBuildProp('ro.build.display.id') || 'Android'

  const systemUuid = Utils.uuid(this.devices.root.name)

  const androidCmdline = [
    `root=UUID=${systemUuid}`,
    `androidboot.selinux=permissive`,
    `androidboot.hardware=${hardware}`,
  ].join(' ')

  // Create extlinux.conf
  const extlinuxDir = path.join(installTarget, 'boot', 'extlinux')
  if (!fs.existsSync(extlinuxDir)) {
    fs.mkdirSync(extlinuxDir, { recursive: true })
  }

  let extlinuxConf = `# extlinux.conf — Android ARM64 (penguins-eggs)
DEFAULT android
TIMEOUT 30
MENU TITLE ${displayId}

LABEL android
    MENU LABEL ${displayId}
    LINUX /boot/${kernelName || 'Image.gz'}
`

  if (initrdName) {
    extlinuxConf += `    INITRD /boot/${initrdName}\n`
  }

  if (fs.existsSync(dtbDir)) {
    extlinuxConf += `    FDTDIR /boot/dtbs/\n`
  }

  extlinuxConf += `    APPEND ${androidCmdline} quiet\n`

  const extlinuxPath = path.join(extlinuxDir, 'extlinux.conf')
  fs.writeFileSync(extlinuxPath, extlinuxConf)
  Utils.warning(`created ${extlinuxPath}`)
}

/**
 * Find the installed kernel image name in /boot.
 */
function findInstalledKernel(installTarget: string): string {
  const bootDir = path.join(installTarget, 'boot')
  if (!fs.existsSync(bootDir)) return ''

  try {
    const files = fs.readdirSync(bootDir)
    // Priority order
    const patterns = ['kernel', 'bzImage', 'vmlinuz', 'Image.gz', 'Image', 'zImage', 'vmlinux']
    for (const pattern of patterns) {
      const match = files.find(f => f === pattern || f.startsWith(pattern + '-'))
      if (match) return match
    }
  } catch { /* ignore */ }

  return ''
}

/**
 * Find the installed initrd image name in /boot.
 */
function findInstalledInitrd(installTarget: string): string {
  const bootDir = path.join(installTarget, 'boot')
  if (!fs.existsSync(bootDir)) return ''

  try {
    const files = fs.readdirSync(bootDir)
    const patterns = ['initrd.img', 'initramfs.img', 'initrd', 'ramdisk.img']
    for (const pattern of patterns) {
      const match = files.find(f => f === pattern || f.startsWith(pattern + '-'))
      if (match) return match
    }
  } catch { /* ignore */ }

  return ''
}
