# Ubuntu 22.04 jammy
---
modules-search: [ local ]

instances:
  - id: before_bootloader_mkdirs
    module: contextualprocess
    config: before_bootloader_mkdirs_context.conf
  - id: before_bootloader
    module: contextualprocess
    config: before_bootloader_context.conf
  - id: after_bootloader
    module: contextualprocess
    config: after_bootloader_context.conf
  - id: logs
    module: shellprocess
    config: shellprocess_logs.conf
  - id: bug-LP#1829805
    module: shellprocess
    config: shellprocess_bug-LP#1829805.conf
  - id: add386arch
    module: shellprocess
    config: shellprocess_add386arch.conf

sequence:
  - show:
      - welcome
      - locale
      - keyboard
      - partition
      {{createUsers}}users
      - summary
  - exec:
      - partition
      - mount
      - unpackfs
      - sources-yolk
      {{hasSystemd}}machineid
      - fstab
      - locale
      - keyboard
      - localecfg
      - luksbootkeyfile
      {{createUsers}}users
      {{hasDisplaymanager}}displaymanager
      - networkcfg
      - hwclock
      - contextualprocess@before_bootloader_mkdirs
      - shellprocess@bug-LP#1829805
      - initramfscfg
      - initramfs
      - grubcfg
      - contextualprocess@before_bootloader
      - bootloader
      - contextualprocess@after_bootloader
      # automirror
      - shellprocess@add386arch
      - packages
      - removeuser
      #  - shellprocess@logs
      - cleanup
      - sources-yolk-undo
      - umount
  - show:
      - finished

branding: {{branding}}
prompt-install: true
dont-chroot: false
oem-setup: false
disable-cancel: false
disable-cancel-during-exec: false