#!/bin/bash
# Rescapp Update-grub run script
# Copyright (C) 2012,2013,2014,2015,2016,2017,2018,2019,2020 Adrian Gibanel Lopez
#
# Rescapp is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# Rescapp is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Rescapp.  If not, see <http://www.gnu.org/licenses/>.

source ${RESCAPP_LIB_FILE}
set -x
set -v

# Check if the Live CD was booted in UEFI mode
function rtux_UEFI_Boot_Check () {

  local EXIT_VALUE=1 # Error by default

  [ -d "${UEFI_DETECTION_DIR}" ]
  EXIT_VALUE=$?

  return ${EXIT_VALUE}

} # function rtux_UEFI_Boot_Check ()


# MAIN PROGRAM

UEFICHECK_OK_STR="This Live CD was booted in UEFI mode :)"
UEFICHECK_KO_STR="This Live CD was NOT booted in UEFI mode :|"

if rtux_UEFI_Boot_Check;
then
  rtux_Message_Success ${UEFICHECK_OK_STR}
else
  rtux_Message_Info ${UEFICHECK_KO_STR}
fi


#
