#!/bin/bash

if [[ $(id -u) -ne 0 ]]; then
    echo "Errore: Questo script deve essere eseguito come root o con sudo." >&2
    exit 1
fi

LOG="./initramfs-log.txt"
CONFDIR="/home/artisan/penguins-eggs/dracut/dracut.conf.d"
LIVE="/home/eggs/iso/live"

dracut --force \
        --confdir $CONFDIR \
        --kmoddir /lib/modules/6.12.48+deb13-amd64 \
        $LIVE/initrd.img-6.12.48+deb13-amd64 6.12.48+deb13-amd64 2>&1| tee $LOG 

scp $LOG artisan@192.168.1.2:/home/artisan

