package setup

import (
	"os"
	"path/filepath"
)

// machineIdConf generates machineid.conf adapted to the current init system.
// Calamares' machineid module runs 'systemd-machine-id-setup' inside the
// target chroot when 'systemd: true' is set. On systemd-less distros (e.g.
// Devuan, Artix, Void) that binary does not exist, so the module exits with
// code 127 and aborts the whole installation.
//
// Detection: if /run/systemd/private exists, systemd is the running init.
// This is the canonical check used by systemd itself and by many other tools.
func machineIdConf() error {
	useSystemd := false
	if _, err := os.Stat("/run/systemd/private"); err == nil {
		useSystemd = true
	}

	var content string
	if useSystemd {
		content = `---
# machineid.conf - generated by coa (systemd detected)
systemd: true
dbus: true
symlink: true
entropy-copy: true
entropy-files:
  - /var/lib/urandom/random-seed
  - /var/lib/systemd/random-seed
`
	} else {
		content = `---
# machineid.conf - generated by coa (systemd not detected)
# 'systemd: false' prevents Calamares from calling systemd-machine-id-setup,
# which does not exist on sysvinit/OpenRC-based distros (Devuan, Artix, etc.)
# and would cause the installation to fail with exit code 127.
# dbus: true generates /var/lib/dbus/machine-id via dbus-uuidgen instead.
systemd: false
dbus: true
symlink: false
entropy-copy: false
`
	}

	targetPath := filepath.Join(InstallerDRoot, "modules", "machineid.conf")
	return os.WriteFile(targetPath, []byte(content), 0644)
}
