#!/bin/bash
# Rescapp Show Log run script
# Copyright (C) 2012,2013,2014,2015,2016,2017,2018,2019,2020 Adrian Gibanel Lopez
#
# Rescapp is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# Rescapp is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Rescapp.  If not, see <http://www.gnu.org/licenses/>.

SHOWLOG_OK_STR="Show log OK!"

source ${RESCAPP_LIB_FILE}

nohup ${FILEMANAGER_COMMAND} file://${RESCAPP_LOG_DIRECTORY} &disown


rtux_Message_Success ${SHOWLOG_OK_STR}

