# custom.yml - Custom configurations for oa-tools
# Override the embedded default settings here.

# remaster:
  # Cannot change the default live user
  # user: "live"

  # You can set a custom password for the live session
  # password: "evolution"

  # You can adjust compression settings to maximize space saving
  compression:
    # Options: zstd, xz, lz4, gzip
    # algorithm: "zstd"
    # Level: for zstd use 1-19
    # level: 3
