Vagrant.configure("2") do |config|

  # https://portal.cloud.hashicorp.com/vagrant/discover
  # you can add a new vm from vagrant/discover
  config.vm.box = "linux-manjaro/26.0.4-260327"

  config.vm.hostname = "linux-manjaro-26.0.4-260327"

  config.vm.provider "virtualbox" do |vb|

    vb.name = "linux-manjaro-26.0.4-260327"

    vb.gui = false

   
    vb.memory = 4096
    vb.cpus = 2

   
    vb.customize ["modifyvm", :id, "--vram", "128"]

  
    vb.customize ["modifyvm", :id, "--accelerate3d", "on"]

    vb.customize ["modifyvm", :id, "--graphicscontroller", "vmsvga"]
  end

  config.vm.synced_folder ".", "/vagrant"
  config.vm.provision "shell", inline: <<-SHELL
    set -eux
    # todo
    sudo apt update -y
    sudo apt install squashfs-tools xorriso live-boot live-boot-initramfs-tools dosfstools mtools rsync git sudo -y
    date
  SHELL
end
