#!/bin/bash
# builders/buildroot/build.sh
#
# Build a cross-compiled recovery image using Buildroot.
#
# Buildroot (https://github.com/buildroot/buildroot) cross-compiles a complete
# Linux system from source for any target architecture. This builder uses
# Buildroot to produce a minimal recovery rootfs, then packages it as a
# SquashFS ISO or EROFS image compatible with penguins-eggs.
#
# Advantages over builders/debian and builders/arch:
#   - Fully cross-compiled: build x86_64 recovery images on ARM, or ARM
#     recovery images on x86_64
#   - Minimal: only the packages you explicitly select
#   - Reproducible: same defconfig + Buildroot version = identical output
#   - Portable: no host distro dependencies beyond make, gcc, and wget
#
# Usage:
#   ./build.sh [options]
#
# Options:
#   --buildroot <path>   Path to Buildroot source tree (required)
#   --defconfig <name>   Buildroot defconfig (default: penguins_recovery_defconfig)
#   --arch <arch>        Target architecture: x86_64|aarch64|riscv64|armv7 (default: x86_64)
#   --format <fmt>       Rootfs format: squashfs|erofs (default: squashfs)
#   --output <path>      Output ISO path (default: recovery-buildroot.iso)
#   --jobs <n>           Parallel build jobs (default: nproc)
#   --no-iso             Produce rootfs image only, skip ISO wrapping
#   --help               Show this help

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
RECOVERY_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"

BUILDROOT_DIR=""
DEFCONFIG="penguins_recovery_defconfig"
ARCH="x86_64"
FORMAT="squashfs"
OUTPUT="recovery-buildroot.iso"
JOBS=$(nproc 2>/dev/null || echo 4)
NO_ISO="false"

RED='\033[1;31m'; GRN='\033[1;32m'; YEL='\033[1;33m'; RST='\033[0m'
info()  { echo -e "${GRN}[buildroot]${RST} $*"; }
warn()  { echo -e "${YEL}[buildroot]${RST} $*"; }
error() { echo -e "${RED}[buildroot]${RST} $*" >&2; }

while [[ $# -gt 0 ]]; do
  case "$1" in
    --buildroot) BUILDROOT_DIR="$2"; shift 2 ;;
    --defconfig) DEFCONFIG="$2";     shift 2 ;;
    --arch)      ARCH="$2";          shift 2 ;;
    --format)    FORMAT="$2";        shift 2 ;;
    --output)    OUTPUT="$2";        shift 2 ;;
    --jobs)      JOBS="$2";          shift 2 ;;
    --no-iso)    NO_ISO="true";      shift ;;
    --help|-h)   sed -n '2,/^$/s/^# //p' "$0"; exit 0 ;;
    *) error "Unknown option: $1"; exit 1 ;;
  esac
done

[[ -z "$BUILDROOT_DIR" ]] && { error "--buildroot required"; exit 1; }
[[ ! -f "${BUILDROOT_DIR}/Makefile" ]] && { error "Buildroot not found at: $BUILDROOT_DIR"; exit 1; }

# ── Step 1: Write penguins-recovery defconfig if not present ─────────────────
info "Step 1/4: Preparing Buildroot configuration"

DEFCONFIG_PATH="${BUILDROOT_DIR}/configs/${DEFCONFIG}"
if [[ ! -f "$DEFCONFIG_PATH" ]]; then
  info "Writing default penguins-recovery defconfig to $DEFCONFIG_PATH"
  cat > "$DEFCONFIG_PATH" << DEFCONFIG_EOF
# Penguins-Recovery minimal rescue system
# Generated by builders/buildroot/build.sh

BR2_${ARCH^^}=y
BR2_OPTIMIZE_2=y

# Kernel
BR2_LINUX_KERNEL=y
BR2_LINUX_KERNEL_DEFCONFIG="${ARCH}"
BR2_LINUX_KERNEL_NEEDS_HOST_OPENSSL=y

# Rootfs
BR2_TARGET_ROOTFS_$(echo "$FORMAT" | tr '[:lower:]' '[:upper:]')=y
BR2_TARGET_ROOTFS_TAR=y

# Recovery tools
BR2_PACKAGE_BASH=y
BR2_PACKAGE_UTIL_LINUX=y
BR2_PACKAGE_UTIL_LINUX_BINARIES=y
BR2_PACKAGE_E2FSPROGS=y
BR2_PACKAGE_DOSFSTOOLS=y
BR2_PACKAGE_PARTED=y
BR2_PACKAGE_BTRFS_PROGS=y
BR2_PACKAGE_CRYPTSETUP=y
BR2_PACKAGE_SQUASHFS=y
BR2_PACKAGE_LVM2=y
BR2_PACKAGE_MDADM=y
BR2_PACKAGE_OPENSSH=y
BR2_PACKAGE_RSYNC=y
BR2_PACKAGE_WGET=y
BR2_PACKAGE_CURL=y
BR2_PACKAGE_NANO=y
BR2_PACKAGE_HTOP=y
BR2_PACKAGE_PCIUTILS=y
BR2_PACKAGE_USBUTILS=y
BR2_PACKAGE_DMIDECODE=y

# Init
BR2_INIT_SYSTEMD=y
BR2_PACKAGE_SYSTEMD_NETWORKD=y

# Bootloader (x86_64 only)
$([ "$ARCH" = "x86_64" ] && echo "BR2_TARGET_GRUB2=y" || echo "# BR2_TARGET_GRUB2 not applicable for $ARCH")
DEFCONFIG_EOF
fi

# Apply defconfig
make -C "$BUILDROOT_DIR" "$DEFCONFIG" O="${BUILDROOT_DIR}/output-recovery"
info "Defconfig applied: $DEFCONFIG"

# ── Step 2: Build ─────────────────────────────────────────────────────────────
info "Step 2/4: Building (this may take a long time)..."
make -C "$BUILDROOT_DIR" -j"$JOBS" O="${BUILDROOT_DIR}/output-recovery"

IMAGES_DIR="${BUILDROOT_DIR}/output-recovery/images"
ROOTFS_IMG="${IMAGES_DIR}/rootfs.${FORMAT}"

[[ ! -f "$ROOTFS_IMG" ]] && { error "Rootfs not found: $ROOTFS_IMG"; exit 1; }
ROOTFS_SIZE=$(du -h "$ROOTFS_IMG" | cut -f1)
info "Rootfs: $ROOTFS_IMG ($ROOTFS_SIZE)"

# ── Step 3: Inject recovery scripts ──────────────────────────────────────────
info "Step 3/4: Injecting recovery scripts"

WORK_DIR="/tmp/buildroot-recovery-work"
ROOTFS_EXTRACT="${WORK_DIR}/rootfs"
mkdir -p "$ROOTFS_EXTRACT"

# Extract tar rootfs (always produced alongside squashfs/erofs)
TAR_ROOTFS="${IMAGES_DIR}/rootfs.tar"
if [[ -f "$TAR_ROOTFS" ]]; then
  tar -xf "$TAR_ROOTFS" -C "$ROOTFS_EXTRACT"
else
  warn "rootfs.tar not found — cannot inject scripts. Enable BR2_TARGET_ROOTFS_TAR=y"
fi

# Copy recovery scripts
SCRIPTS_DEST="${ROOTFS_EXTRACT}/usr/local/bin"
mkdir -p "$SCRIPTS_DEST"
for script in \
  "${RECOVERY_ROOT}/common/scripts/chroot-rescue.sh" \
  "${RECOVERY_ROOT}/common/scripts/btrfs-rescue.sh" \
  "${RECOVERY_ROOT}/common/scripts/erofs-rescue.sh" \
  "${RECOVERY_ROOT}/common/scripts/detect-disks.sh" \
  "${RECOVERY_ROOT}/common/scripts/grub-restore.sh" \
  "${RECOVERY_ROOT}/common/scripts/password-reset.sh" \
  "${RECOVERY_ROOT}/common/scripts/uefi-repair.sh" \
  ; do
  if [[ -f "$script" ]]; then
    cp "$script" "$SCRIPTS_DEST/"
    chmod +x "${SCRIPTS_DEST}/$(basename "$script")"
    info "  + $(basename "$script")"
  fi
done

# Add motd
if [[ -f "${RECOVERY_ROOT}/common/branding/motd.txt" ]]; then
  cp "${RECOVERY_ROOT}/common/branding/motd.txt" "${ROOTFS_EXTRACT}/etc/motd"
fi

# Repack rootfs with injected scripts
info "Repacking rootfs with recovery scripts..."
if [[ "$FORMAT" == "squashfs" ]]; then
  mksquashfs "$ROOTFS_EXTRACT" "${WORK_DIR}/rootfs.squashfs" \
    -comp zstd -Xcompression-level 9 -noappend -no-progress
  ROOTFS_IMG="${WORK_DIR}/rootfs.squashfs"
elif [[ "$FORMAT" == "erofs" ]]; then
  mkfs.erofs -zlz4hc,9 "${WORK_DIR}/rootfs.erofs" "$ROOTFS_EXTRACT"
  ROOTFS_IMG="${WORK_DIR}/rootfs.erofs"
fi

# ── Step 4: Wrap into ISO (optional) ─────────────────────────────────────────
if [[ "$NO_ISO" == "true" ]]; then
  info "Step 4/4: Skipping ISO wrapping (--no-iso)"
  info "Rootfs image: $ROOTFS_IMG"
else
  info "Step 4/4: Building ISO"

  ISO_WORK="${WORK_DIR}/iso"
  mkdir -p "${ISO_WORK}/live" "${ISO_WORK}/boot/grub"

  cp "$ROOTFS_IMG" "${ISO_WORK}/live/filesystem.${FORMAT}"

  # Copy kernel and initrd from Buildroot output
  KERNEL=$(find "$IMAGES_DIR" -maxdepth 1 -name "bzImage" -o -name "Image" -o -name "zImage" | head -1)
  INITRD=$(find "$IMAGES_DIR" -maxdepth 1 -name "*.cpio*" -o -name "rootfs.cpio" | head -1)

  [[ -n "$KERNEL" ]] && cp "$KERNEL" "${ISO_WORK}/boot/vmlinuz"
  [[ -n "$INITRD" ]] && cp "$INITRD" "${ISO_WORK}/boot/initrd.img"

  # Write GRUB config
  cat > "${ISO_WORK}/boot/grub/grub.cfg" << GRUB_EOF
set timeout=5
set default=0

menuentry "Penguins Recovery (Buildroot ${ARCH})" {
  linux /boot/vmlinuz quiet splash
  initrd /boot/initrd.img
}
GRUB_EOF

  if command -v xorriso &>/dev/null; then
    xorriso -as mkisofs -o "$OUTPUT" \
      -b boot/grub/i386-pc/eltorito.img 2>/dev/null \
      -no-emul-boot -boot-load-size 4 -boot-info-table \
      "$ISO_WORK" 2>/dev/null || \
    xorriso -as mkisofs -o "$OUTPUT" "$ISO_WORK"
    info "ISO: $OUTPUT ($(du -h "$OUTPUT" | cut -f1))"
  else
    warn "xorriso not found — skipping ISO. Rootfs image: $ROOTFS_IMG"
  fi
fi

info "============================================"
info "Buildroot recovery build complete!"
info "  Arch:    $ARCH"
info "  Format:  $FORMAT"
info "  Rootfs:  $ROOTFS_IMG"
[[ "$NO_ISO" == "false" ]] && info "  ISO:     $OUTPUT"
info "============================================"
