#!/bin/bash

################################################
# pre-remove script
################################################

# pulizia dei link non rimovibili da apt
rm /usr/lib/penguins-eggs/conf/distros -rf

# Rimuoviamo il manuale di eggs
if [ -f "/usr/share/man/man1/eggs.1.gz" ]; then
    rm /usr/share/man/man1/eggs.1
    mandb >/dev/null
fi

# Rimuoviamo eggs.bash per l'autocomplete
if [ -f "/etc/bash_completion.d/eggs.bash" ]; then
    rm /etc/bash_completion.d/eggs.bash
fi

exit 0