#!/bin/bash

################################################
# pre-remove script
################################################

# pulizia dei link non rimovibili da apt
rm -rf /usr/lib/penguins-eggs/conf/distros

# remove man eggs
if [ -f "/usr/share/man/man1/eggs.1.gz" ]; then
    rm -f /usr/share/man/man1/eggs.1.gz
fi

# remove eggs.bash 
if [ -f "/etc/bash_completion.d/eggs.bash" ]; then
    rm -f /etc/bash_completion.d/eggs.bash
fi

# remove calamares customization
FILE=/var/lib/dpkg/info/calamares.list
if [ -f "$FILE" ]; then
    rm -rf /etc/calamares

    # remove scripts calamares/krill
    rm -f /usr/sbin/bootloader-config.sh
    rm -f /usr/sbin/remove-link.sh
    rm -f /usr/sbin/sources-yolk.sh

    # remove eggs calamares-modules x86_64
    rm -rf /usr/lib/x86_64-linux-gnu/calamares/modules/bootloader-config  
    rm -rf /usr/lib/x86_64-linux-gnu/calamares/modules/remove-link  
    rm -rf /usr/lib/x86_64-linux-gnu/calamares/modules/sources-yolk  
    rm -rf /usr/lib/x86_64-linux-gnu/calamares/modules/sources-yolk-undo
    rm -rf /usr/lib/x86_64-linux-gnu/calamares/modules/cleanup

    # remove eggs calamares-modules i386
    rm -rf /usr/lib/i386-linux-gnu/calamares/modules/bootloader-config  
    rm -rf /usr/lib/i386-linux-gnu/calamares/modules/remove-link  
    rm -rf /usr/lib/i386-linux-gnu/calamares/modules/sources-yolk  
    rm -rf /usr/lib/i386-linux-gnu/calamares/modules/sources-yolk-undo
    rm -rf /usr/lib/i386-linux-gnu/calamares/modules/cleanup
fi

exit 0