# settings.conf Universale (Gestito da COA)
---
modules-search:
  - local

oem-setup: false
disable-cancel: false
disable-cancel-during-exec: false
quit-at-end: false

instances:
  - id:       oa_bootloader
    module:   shellprocess
    config:   shellprocess_oa_bootloader.conf
  - id:       oa_removelink
    module:   shellprocess
    config:   shellprocess_oa_removelink.conf
    
sequence:
  - show:
      - welcome
      - locale
      - keyboard
      - partition
      - users
      - summary
  - exec:
      # clearmounts     # Non è sempre presente
      - partition       # Crea le partizioni fisiche
      - mount           # Le monta in /tmp/calamares-root
      - unpackfs        # Scompatta il tuo filesystem.squashfs
      - machineid       # Genera un nuovo /etc/machine-id
      - fstab           # Crea l'fstab con i nuovi UUID
      - locale          # Imposta la lingua base
      - keyboard        # Imposta la tastiera
      - localecfg       # Applica la localizzazione (se supportato)
      - users           # Crea l'utente senza controlli password fastidiosi
      - displaymanager  # Imposta autologin
      - shellprocess@oa_removelink 
      - shellprocess@oa_bootloader
      - removeuser      # rimuove utente live
      - umount          # Smonta tutto a lavoro finito
  - show:
      - finished

branding: eggs
prompt-install: false
dont-chroot: false