Vagrant.configure("2") do |config|

  # https://portal.cloud.hashicorp.com/vagrant/discover
  # you can add a new vm from vagrant/discover
  config.vm.box = "cloud-image/debian-13"

  config.vm.hostname = "cloud-image-debian-13"

  config.vm.provider "virtualbox" do |vb|

    vb.name = "cloud-image-debian-13"

    vb.gui = false

   
    vb.memory = 4096
    vb.cpus = 2

   
    vb.customize ["modifyvm", :id, "--vram", "128"]

  
    vb.customize ["modifyvm", :id, "--accelerate3d", "on"]

    vb.customize ["modifyvm", :id, "--graphicscontroller", "vmsvga"]
  end

  config.vm.synced_folder ".", "/vagrant"

end