/**
 * ./src/classes/ovary.d/android/android-ota.ts
 * penguins-eggs — Android backend
 * license: MIT
 *
 * Generates OTA (Over-The-Air) update packages for Android.
 *
 * Two OTA formats:
 *   1. Legacy "block-based" OTA zip (Android 5-12 style)
 *      - Contains updater-script + partition images
 *      - Signed with signapk.jar or openssl
 *      - Flashable via recovery (TWRP, LineageOS recovery)
 *
 *   2. Payload-based A/B OTA (Android 7+ with A/B partitions)
 *      - Contains payload.bin (delta or full)
 *      - Uses update_engine on device
 *      - Compatible with LineageOS updater
 *
 * This module implements the legacy format (most widely compatible)
 * and generates metadata compatible with lineageos-infra/updater.
 */

import crypto from 'node:crypto'
import fs from 'node:fs'
import path from 'node:path'

import { readBuildProp } from '../../../android/prop-reader.js'
import { exec, shx } from '../../../lib/utils.js'
import Utils from '../../utils.js'

export interface IOtaConfig {
  /** Output zip file path */
  outputPath: string
  /** Partition images to include */
  images: {
    boot?: string
    system?: string
    vendor?: string
    vbmeta?: string
  }
  /** Build timestamp (epoch seconds) */
  timestamp: number
  /** Build fingerprint */
  fingerprint: string
  /** Device codename */
  device: string
  /** ROM name */
  romName: string
  /** ROM version */
  romVersion: string
  /** Android SDK version */
  sdkVersion: string
  /** Whether to compress images with brotli */
  useBrotli: boolean
  /** Verbose output */
  verbose: boolean
}

export interface IOtaMetadata {
  /** Metadata for LineageOS-compatible updater */
  datetime: number
  filename: string
  id: string
  romtype: string
  size: number
  url: string
  version: string
}

/**
 * Generate an updater-script for the OTA zip.
 * This is the script that recovery executes to flash the update.
 */
function generateUpdaterScript(config: IOtaConfig): string {
  const lines: string[] = [
    `# OTA updater-script generated by penguins-eggs`,
    `# ${config.romName} ${config.romVersion}`,
    `# Device: ${config.device}`,
    `# Timestamp: ${new Date(config.timestamp * 1000).toISOString()}`,
    ``,
    `ui_print("Installing ${config.romName} ${config.romVersion}...");`,
    `ui_print("Device: ${config.device}");`,
    `ui_print("");`,
    ``,
    `# Mount system partition`,
    `mount("ext4", "EMMC", "/dev/block/by-name/system", "/system");`,
    ``,
  ]

  // Add image flashing commands
  if (config.images.boot) {
    lines.push(`ui_print("Flashing boot image...");`)
    lines.push(`package_extract_file("boot.img", "/dev/block/by-name/boot");`)
    lines.push(``)
  }

  if (config.images.system) {
    lines.push(`ui_print("Flashing system image...");`)
    lines.push(`block_image_update("/dev/block/by-name/system", package_extract_file("system.transfer.list"), "system.new.dat.br", "system.patch.dat");`)
    lines.push(``)
  }

  if (config.images.vendor) {
    lines.push(`ui_print("Flashing vendor image...");`)
    lines.push(`block_image_update("/dev/block/by-name/vendor", package_extract_file("vendor.transfer.list"), "vendor.new.dat.br", "vendor.patch.dat");`)
    lines.push(``)
  }

  if (config.images.vbmeta) {
    lines.push(`ui_print("Flashing vbmeta...");`)
    lines.push(`package_extract_file("vbmeta.img", "/dev/block/by-name/vbmeta");`)
    lines.push(``)
  }

  lines.push(`# Unmount`)
  lines.push(`unmount("/system");`)
  lines.push(``)
  lines.push(`ui_print("Installation complete!");`)
  lines.push(`ui_print("");`)

  return lines.join('\n')
}

/**
 * Generate OTA metadata JSON compatible with LineageOS updater.
 */
export function generateOtaMetadata(config: IOtaConfig, fileSize: number): IOtaMetadata {
  // Generate a unique ID from fingerprint + timestamp
  const id = crypto
    .createHash('sha256')
    .update(`${config.fingerprint}-${config.timestamp}`)
    .digest('hex')
    .slice(0, 32)

  return {
    datetime: config.timestamp,
    filename: path.basename(config.outputPath),
    id,
    romtype: 'UNOFFICIAL',
    size: fileSize,
    url: '',
    version: config.romVersion,
  }
}

/**
 * Compress a file with brotli (used for system.new.dat → system.new.dat.br).
 */
async function brotliCompress(inputPath: string, outputPath: string, verbose = false): Promise<void> {
  if (shx.exec('which brotli', { silent: true }).code !== 0) {
    throw new Error('brotli not found. Install with: apt install brotli')
  }

  Utils.warning(`compressing ${path.basename(inputPath)} with brotli`)
  const result = await exec(`brotli -j ${inputPath} -o ${outputPath}`, Utils.setEcho(verbose))
  if (result.code !== 0) {
    throw new Error(`brotli compression failed for ${inputPath}`)
  }
}

/**
 * Create a flashable OTA zip package.
 *
 * Structure of the output zip:
 *   META-INF/
 *     com/google/android/
 *       update-binary     (recovery binary)
 *       updater-script    (flash instructions)
 *   boot.img              (optional)
 *   system.new.dat.br     (brotli-compressed system image)
 *   system.transfer.list  (block transfer list)
 *   system.patch.dat      (empty for full OTA)
 *   vendor.new.dat.br     (optional)
 *   vendor.transfer.list  (optional)
 *   vbmeta.img            (optional)
 *   metadata              (OTA metadata)
 */
export async function createOtaPackage(config: IOtaConfig): Promise<string> {
  const workDir = '/tmp/eggs-android-ota-work'
  await exec(`rm -rf ${workDir}`)

  // Create directory structure
  const metaInfDir = path.join(workDir, 'META-INF', 'com', 'google', 'android')
  await exec(`mkdir -p ${metaInfDir}`)

  // Generate updater-script
  const updaterScript = generateUpdaterScript(config)
  fs.writeFileSync(path.join(metaInfDir, 'updater-script'), updaterScript)

  // Create a minimal update-binary (shell script that interprets updater-script)
  // In practice, this would be the real update-binary from AOSP recovery
  const updateBinary = `#!/sbin/sh
# Minimal update-binary for penguins-eggs OTA
# In production, replace with AOSP's update-binary

OUTFD=$2
ZIPFILE=$3

ui_print() {
  echo "ui_print $1" > /proc/self/fd/$OUTFD
  echo "ui_print" > /proc/self/fd/$OUTFD
}

ui_print "penguins-eggs OTA installer"
ui_print "Extracting files..."

cd /tmp
unzip -o "$ZIPFILE" -x META-INF/*

# Flash boot if present
if [ -f boot.img ]; then
  ui_print "Flashing boot..."
  dd if=boot.img of=/dev/block/by-name/boot
fi

# Flash vbmeta if present
if [ -f vbmeta.img ]; then
  ui_print "Flashing vbmeta..."
  dd if=vbmeta.img of=/dev/block/by-name/vbmeta
fi

ui_print "Done!"
exit 0
`
  fs.writeFileSync(path.join(metaInfDir, 'update-binary'), updateBinary)
  await exec(`chmod +x ${path.join(metaInfDir, 'update-binary')}`)

  // Copy partition images
  if (config.images.boot && fs.existsSync(config.images.boot)) {
    Utils.warning('adding boot.img to OTA package')
    await exec(`cp ${config.images.boot} ${workDir}/boot.img`)
  }

  if (config.images.system && fs.existsSync(config.images.system)) {
    if (config.useBrotli && shx.exec('which brotli', { silent: true }).code === 0) {
      // Compress with brotli for smaller OTA
      await brotliCompress(config.images.system, path.join(workDir, 'system.new.dat.br'), config.verbose)
    } else {
      // Copy raw
      Utils.warning('adding system.img to OTA package')
      await exec(`cp ${config.images.system} ${workDir}/system.img`)
    }

    // Create transfer list (simplified — full OTA, not incremental)
    const sysSize = fs.statSync(config.images.system).size
    const blockCount = Math.ceil(sysSize / 4096)
    const transferList = [
      '4',                    // version
      `${blockCount}`,        // total blocks
      '0',                    // stash entries
      '0',                    // max stash
      `new 0-${blockCount - 1}`, // transfer command: write all blocks
    ].join('\n')
    fs.writeFileSync(path.join(workDir, 'system.transfer.list'), transferList)

    // Empty patch file (full OTA, no patches)
    fs.writeFileSync(path.join(workDir, 'system.patch.dat'), '')
  }

  if (config.images.vendor && fs.existsSync(config.images.vendor)) {
    if (config.useBrotli && shx.exec('which brotli', { silent: true }).code === 0) {
      await brotliCompress(config.images.vendor, path.join(workDir, 'vendor.new.dat.br'), config.verbose)
    } else {
      Utils.warning('adding vendor.img to OTA package')
      await exec(`cp ${config.images.vendor} ${workDir}/vendor.img`)
    }

    const vendorSize = fs.statSync(config.images.vendor).size
    const vendorBlocks = Math.ceil(vendorSize / 4096)
    const vendorTransferList = [
      '4',
      `${vendorBlocks}`,
      '0',
      '0',
      `new 0-${vendorBlocks - 1}`,
    ].join('\n')
    fs.writeFileSync(path.join(workDir, 'vendor.transfer.list'), vendorTransferList)
    fs.writeFileSync(path.join(workDir, 'vendor.patch.dat'), '')
  }

  if (config.images.vbmeta && fs.existsSync(config.images.vbmeta)) {
    await exec(`cp ${config.images.vbmeta} ${workDir}/vbmeta.img`)
  }

  // Write OTA metadata properties file
  const metadataProps = [
    `ota-type=FULL`,
    `post-build=${config.fingerprint}`,
    `post-build-incremental=${config.timestamp}`,
    `post-sdk-level=${config.sdkVersion}`,
    `post-timestamp=${config.timestamp}`,
    `pre-device=${config.device}`,
  ].join('\n')
  fs.writeFileSync(path.join(workDir, 'metadata'), metadataProps)

  // Create the zip
  const outputDir = path.dirname(config.outputPath)
  if (!fs.existsSync(outputDir)) {
    await exec(`mkdir -p ${outputDir}`)
  }

  Utils.warning(`creating OTA zip: ${path.basename(config.outputPath)}`)
  const result = await exec(
    `cd ${workDir} && zip -r ${config.outputPath} . -x '*.DS_Store'`,
    Utils.setEcho(config.verbose)
  )

  if (result.code !== 0) {
    throw new Error('Failed to create OTA zip')
  }

  // Sign the zip if signapk is available
  await signOtaZip(config.outputPath, config.verbose)

  // Generate checksums
  await exec(`md5sum ${config.outputPath} > ${config.outputPath.replace('.zip', '.md5')}`)
  await exec(`sha256sum ${config.outputPath} > ${config.outputPath.replace('.zip', '.sha256')}`)

  // Cleanup
  await exec(`rm -rf ${workDir}`)

  return config.outputPath
}

/**
 * Sign an OTA zip with test keys or provided keys.
 * Uses signapk.jar if available, otherwise uses openssl.
 */
async function signOtaZip(zipPath: string, verbose = false): Promise<void> {
  // Try signapk.jar (AOSP tool)
  const signapkPaths = [
    '/usr/share/android-sdk/build-tools/signapk.jar',
    '/opt/android-sdk/build-tools/signapk.jar',
    `${process.env.ANDROID_HOME || ''}/build-tools/signapk.jar`,
  ]

  let signapkJar = ''
  for (const sp of signapkPaths) {
    if (fs.existsSync(sp)) {
      signapkJar = sp
      break
    }
  }

  if (signapkJar) {
    // Use AOSP test keys if no custom keys provided
    const testKeyDir = path.dirname(signapkJar)
    const certPem = path.join(testKeyDir, 'testkey.x509.pem')
    const keyPk8 = path.join(testKeyDir, 'testkey.pk8')

    if (fs.existsSync(certPem) && fs.existsSync(keyPk8)) {
      const signedPath = zipPath + '.signed'
      Utils.warning('signing OTA zip with signapk')
      const result = await exec(
        `java -jar ${signapkJar} ${certPem} ${keyPk8} ${zipPath} ${signedPath}`,
        Utils.setEcho(verbose)
      )

      if (result.code === 0) {
        await exec(`mv ${signedPath} ${zipPath}`)
        return
      }
    }
  }

  // Fallback: no signing (warn user)
  Utils.warning('signapk not available — OTA zip is unsigned. Flash with TWRP signature verification disabled.')
}

/**
 * Generate a LineageOS-updater-compatible JSON response.
 * This can be served from a web server for OTA updates.
 */
export function generateUpdaterJson(
  metadata: IOtaMetadata,
  baseUrl: string
): string {
  const response = {
    response: [
      {
        ...metadata,
        url: `${baseUrl}/${metadata.filename}`,
      },
    ],
  }

  return JSON.stringify(response, null, 2)
}

/**
 * Generate GrapheneOS-style release metadata.
 *
 * GrapheneOS uses a different OTA format than LineageOS:
 *   - releases.grapheneos.org serves factory images and OTA packages
 *   - OTA metadata is a simple text file with version code
 *   - Factory images are signed with AVB and include all partitions
 *
 * Based on patterns from:
 *   - releases.grapheneos.org: release hosting and metadata
 *   - infrastructure: deployment and signing pipeline
 *   - script: build automation
 */
export interface IGrapheneOSReleaseMetadata {
  /** Device codename (e.g., "husky", "shiba") */
  device: string
  /** Version code (e.g., "2024030100") */
  versionCode: string
  /** Release channel */
  channel: 'alpha' | 'beta' | 'stable'
  /** Timestamp */
  datetime: number
  /** Incremental version for delta OTA */
  incremental: string
  /** Factory image filename */
  factoryFilename: string
  /** OTA filename */
  otaFilename: string
  /** SHA256 of factory image */
  factorySha256: string
  /** SHA256 of OTA package */
  otaSha256: string
}

/**
 * Generate GrapheneOS-compatible release metadata.
 */
export function generateGrapheneOSMetadata(
  device: string,
  versionCode: string,
  channel: 'alpha' | 'beta' | 'stable' = 'stable'
): IGrapheneOSReleaseMetadata {
  return {
    channel,
    datetime: Math.floor(Date.now() / 1000),
    device,
    factoryFilename: `${device}-factory-${versionCode}.zip`,
    factorySha256: '',
    incremental: versionCode,
    otaFilename: `${device}-ota_update-${versionCode}.zip`,
    otaSha256: '',
    versionCode,
  }
}

/**
 * Generate the OTA update metadata text file used by GrapheneOS updater.
 * This is a simple format: one line with the version code.
 * The updater checks this against the installed version to determine
 * if an update is available.
 */
export function generateGrapheneOSOtaMetadataFile(
  device: string,
  versionCode: string,
  channel: 'alpha' | 'beta' | 'stable' = 'stable'
): string {
  // GrapheneOS uses a simple text format for the update check endpoint
  // The device checks: https://releases.grapheneos.org/{device}-{channel}
  return `${versionCode}\n`
}
