alias debug='podman --log-level debug info'
alias nano='rnano'
alias ns='netstat -lptun'
alias log='journalctl --user'
alias cp='rm -i'
alias cp='cp -i'
alias df='df -h'
alias ls='ls --color=auto --group-directories-first'
alias ll='ls -l'
alias la='ls -a'
alias notes='$EDITOR ~/notes'

# services
alias start='systemctl --user start'
alias stop='systemctl --user stop'
alias restart='systemctl --user restart'
alias reload='systemctl --user reload'
alias enable='systemctl --user enable'
alias disable='systemctl --user disable'
alias status='systemctl --user status'
