#!/bin/bash -e


function press_a_key_to_continue {
   read -rp ">> Press enter to continue or CTRL-C to abort."
}


function kill {
    sudo eggs kill
}

function produce {
    sudo eggs dad --default
    sudo eggs tools clean
    sudo eggs produce
}

# main
clear
echo ">>> LOVE: the simplest way to get a child!"
echo
echo "1) sudo eggs kill"
echo "2) sudo eggs dad --default"
echo "3) sudo eggs tools clean"
echo "4) sudo eggs produce"
press_a_key_to_continue
kill
produce
