#!/bin/bash -e
clear
echo ">>> LOVE: A fast way to get a child"

function kill {
    sudo eggs kill
}

function produce {
    sudo eggs dad --default
    sudo eggs tools clean
    sudo eggs produce
}

# main
kill
produce
