#!/bin/bash -e

function press_a_key_to_continue {
   read -rp ">> Press enter to continue or CTRL-C to abort."
}

# main
if command -v sudo >/dev/null 2>&1; then
    SUDO='sudo'
else
    SUDO='doas'
fi
clear
echo ">>> L O V E :  the simplest way to get a child!"
echo
echo "1) $SUDO eggs kill"
echo "2) $SUDO eggs dad --default"
echo "3) $SUDO eggs tools clean"
echo "4) $SUDO eggs produce --pendrive"
echo
press_a_key_to_continue
$SUDO eggs kill
$SUDO eggs dad --default
$SUDO eggs tools clean
$SUDO eggs produce --pendrive
