#!/bin/sh
clear
echo ">>> Re-install Eggs Saving Yolk"
tmpDir=$(mktemp -d)
sudo mv /var/local/yolk "${tmpDir}"
sudo apt -y purge eggs
sudo dpkg -i /tmp/eggs*.deb
sudo mv "${tmpDir}/yolk" /var/local
sudo eggs dad -d
