#!/bin/bash
rm -rf ~/bootloaders*
mkdir ~/bootloaders
cp -r /usr/lib/grub ~/bootloaders
cp -r /usr/lib/ipxe ~/bootloaders
cp -r /usr/lib/ISOLINUX ~/bootloaders
cp -r /usr/lib/PXELINUX ~/bootloaders
cp -r /usr/lib/shim ~/bootloaders
cp -r /usr/lib/syslinux ~/bootloaders
tar -cvzf ~/bootloaders.tar.gs ~/bootloaders
