Vagrant.configure("2") do |config|
  # Usiamo 'debian' come nome interno univoco
  config.vm.define "debian" do |node|
    node.vm.box = "cloud-image/debian-13"
    node.vm.hostname = "debian-egg"

    node.vm.provider "virtualbox" do |vb|
      vb.name = "debian-egg"
      vb.gui = false
      vb.memory = 4096
      vb.cpus = 2
      # ... restano i tuoi customize ...
    end

    node.vm.synced_folder ".", "/vagrant"

    node.vm.provision "shell", inline: <<-SHELL
      set -eux
      sudo apt update -y
      sudo apt install squashfs-tools xorriso live-boot live-boot-initramfs-tools dosfstools mtools rsync git sudo -y
    SHELL
  end
end
