Vagrant.configure("2") do |config|
  # Nome macchina univoco per la matrice
  config.vm.define "debian" do |node|
    node.vm.box = "cloud-image/debian-13"
    node.vm.hostname = "debian-egg"

    node.vm.provider "libvirt" do |lv|
      lv.memory = 4096
      lv.cpus = 2
    end

    node.vm.synced_folder "../..", "/vagrant", 
      type: "9p", 
      disabled: false, 
      mount_options: ["version=9p2000.L", "trans=virtio", "access=any", "uid=1000", "gid=1000"]

    # Provisioning blindato
    node.vm.provision "shell", inline: <<-SHELL
      set -eux
      
      # Abilita sudo senza password
      echo "vagrant ALL=(ALL) NOPASSWD: ALL" > /etc/sudoers.d/vagrant
      chmod 0440 /etc/sudoers.d/vagrant

      # Aggiornamento e installazione
      sudo apt update -y
      sudo apt install -y squashfs-tools xorriso live-boot live-boot-initramfs-tools dosfstools mtools rsync git sudo
    SHELL
  end
end
