#!/bin/bash
# Rescapp Fsck run script
# Copyright (C) 2012,2013,2014,2015,2016,2017,2018,2019,2020 Adrian Gibanel Lopez
#
# Rescapp is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# Rescapp is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Rescapp.  If not, see <http://www.gnu.org/licenses/>.

source ${RESCAPP_LIB_FILE}

set -x
set -v


# fsck Main program

FSCK_FORCED_OK_STR="Filesystem check with automatic fix was OK! :)"
FSCK_FORCED_KO_STR="Filesystem check with automatic fix failed! :("
FSCK_FORCED_RUNNING_STR="Performing Filesystem check with automatic fix"
FSCK_PARTITIONS_NOT_FOUND="No partitions were found or chosen."

SELECTED_PARTITION=$(rtux_Choose_Partition)

if [ "x${SELECTED_PARTITION}" != "x" ] ; then
    if ( rtux_Run_Show_Progress "${FSCK_FORCED_RUNNING_STR}" rtux_Fsck_Forced ${SELECTED_PARTITION} ) ; then
        rtux_Message_Success ${FSCK_FORCED_OK_STR}
    else
        rtux_Message_Failure ${FSCK_FORCED_KO_STR}
    fi
else
    rtux_Message_Warning ${FSCK_PARTITIONS_NOT_FOUND}
    rtux_Message_Failure ${FSCK_FORCED_KO_STR}
fi
