name: _108-vagrant-opensuse-leap-15.6

# only manual, thanks
on: 
  workflow_dispatch:
  
jobs:
  build:

    runs-on: ubuntu-latest
    timeout-minutes: 120

    steps:
    - uses: actions/checkout@v6

    - name: run buidl and test
      run: |
        ./tests/108-vagrant-opensuse-leap-15.6/vagrant.install.build.test.sh

