name: _106-vagrant-centos-10-stream

# only manual, thanks
on: 
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest
    timeout-minutes: 120

    steps:
    - uses: actions/checkout@v6

    - name: run buidl and test
      run: |
        ./tests/106-vagrant-centos-10-stream/vagrant.install.build.test.sh

