package builder

import (
	"fmt"
	"os"
	"os/exec"
	"path/filepath"

	sysctx "coa/pkg/context" // Il nostro scudo contestuale
)

// packAlpine prepara l'ambiente sorgente e l'APKBUILD per Alpine Linux
// RISPETTA IL PATTO: Sfrutta il RuntimeContext per non usurare i dischi.
func packAlpine(baseVer string, relNum string, ctx sysctx.RuntimeContext) {
	LogBuild("Iniziando la preparazione dei sorgenti Alpine (APKBUILD)...")

	// 1. Il tavolo da lavoro
	buildDir := filepath.Join(ctx.BaseBuildDir, "alpine-build")
	stagingDir := filepath.Join(buildDir, "staging")
	os.RemoveAll(buildDir)

	// 2. Creazione struttura in 'staging'
	dirs := []string{
		filepath.Join(stagingDir, "usr/bin"),
		filepath.Join(stagingDir, "etc/oa-tools.d/brain.d"),
		filepath.Join(stagingDir, "usr/share/man/man1"),
		filepath.Join(stagingDir, "usr/share/bash-completion/completions"),
		filepath.Join(stagingDir, "usr/share/zsh/vendor-completions"),
		filepath.Join(stagingDir, "usr/share/fish/vendor_completions.d"),
	}
	for _, dir := range dirs {
		os.MkdirAll(dir, 0755)
	}

	// 3. Binari
	binPath := filepath.Join(stagingDir, "usr/bin")
	copyFile(filepath.Join(ctx.BaseBuildDir, "oa", "oa"), filepath.Join(binPath, "oa"))
	copyFile(filepath.Join(ctx.BaseBuildDir, "coa", "coa"), filepath.Join(binPath, "coa"))
	os.Chmod(filepath.Join(binPath, "oa"), 0755)
	os.Chmod(filepath.Join(binPath, "coa"), 0755)
	os.Symlink("coa", filepath.Join(binPath, "eggs"))

	// 4. Configurazione YAML e Brain
	confDest := filepath.Join(stagingDir, "etc/oa-tools.d")
	brainDest := filepath.Join(confDest, "brain.d")

	// Uniamo cleanVer e relNum per la versione tracciata nello yaml
	fullVersion := fmt.Sprintf("%s-%s", cleanVer, relNum)

	oaYamlContent := fmt.Sprintf(`---
system:
  dialect: "oa"
  version: "%s"
wardrobe:
  root: "~/.oa-wardrobe"
  repo: "https://github.com/pieroproietti/oa-wardrobe.git"
remaster:
  default_user: "artisan"
  work_dir: "/home/eggs"
`, fullVersion)
	os.WriteFile(filepath.Join(confDest, "oa-tools.yaml"), []byte(oaYamlContent), 0644)
	brainSrc := filepath.Join(ctx.CoaDir, "brain.d")
	exec.Command("sh", "-c", fmt.Sprintf("cp -r %s/* %s/", brainSrc, brainDest)).Run()

	// 5. Documentazione e Completamenti
	docSourceDir := filepath.Join(ctx.BaseBuildDir, "docs")
	manDir := filepath.Join(stagingDir, "usr/share/man/man1")
	exec.Command("sh", "-c", fmt.Sprintf("cp %s/man/*.1 %s/ && gzip -9 %s/*.1", docSourceDir, manDir, manDir)).Run()

	bashTarget := filepath.Join(stagingDir, "usr/share/bash-completion/completions/coa")
	copyFile(filepath.Join(docSourceDir, "completion/coa.bash"), bashTarget)
	copyFile(filepath.Join(docSourceDir, "completion/coa.zsh"), filepath.Join(stagingDir, "usr/share/zsh/vendor-completions/_coa"))
	copyFile(filepath.Join(docSourceDir, "completion/coa.fish"), filepath.Join(stagingDir, "usr/share/fish/vendor_completions.d/coa.fish"))
	os.Symlink("coa", filepath.Join(stagingDir, "usr/share/bash-completion/completions/eggs"))
	os.Symlink("_coa", filepath.Join(stagingDir, "usr/share/zsh/vendor-completions/_eggs"))
	os.Symlink("coa.fish", filepath.Join(stagingDir, "usr/share/fish/vendor_completions.d/eggs.fish"))

	f, err := os.OpenFile(bashTarget, os.O_APPEND|os.O_WRONLY, 0644)
	if err == nil {
		f.WriteString("\n# eggs alias completion support\ncomplete -o default -F __start_coa eggs\n")
		f.Close()
	}

	// ---------------------------------------------------------
	// IL MAGICO APKBUILD (Stile Arch PKGBUILD)
	// ---------------------------------------------------------
	apkbuildContent := fmt.Sprintf(`# Generated by oa-tools builder
pkgname=oa-tools
pkgver=%s
pkgrel=%s
pkgdesc="coa is the mind and oa the arm"
url="https://penguins-eggs.net"
arch="x86_64"
license="MIT"
maintainer="Piero Proietti <piero.proietti@gmail.com>"
depends="squashfs-tools xorriso dosfstools mtools rsync git sudo grub-efi"
options="!check" # Saltiamo i test automatici di Alpine per ora

# La funzione package si limita a travasare la nostra cartella staging
package() {
	mkdir -p "$pkgdir"
	cp -a "$startdir/staging/"* "$pkgdir/"
}
`, baseVer, relNum)

	os.WriteFile(filepath.Join(buildDir, "APKBUILD"), []byte(apkbuildContent), 0644)

	// 6. Consegna dell'ambiente di build (Nessuna esecuzione di abuild)
	switch ctx.EnvType {
	case sysctx.EnvVagrant:
		LogBuild("[Vagrant Mode] Ambiente Alpine protetto in RAM: %s", buildDir)
	case sysctx.EnvCI:
		LogBuild("[CI Mode] Ambiente Alpine rilasciato nel workspace: %s", buildDir)
	default:
		finalTargetDir := filepath.Join(ctx.ProjRoot)
		os.RemoveAll(finalTargetDir) // Puliamo eventuali build precedenti

		// Copiamo l'intera cartella pronta per abuild nella root
		cmd := exec.Command("cp", "-a", buildDir, finalTargetDir)
		if err := cmd.Run(); err == nil {
			LogBuild("✅ Ambiente sorgente Alpine pronto in: %s", finalTargetDir)
			LogBuild("👉 Per compilare manualmente: cd alpine-build && abuild -r")
		} else {
			LogError("Impossibile copiare l'ambiente nella repo: %v", err)
		}
	}

	// Pulizia del temp originale se siamo in modalità standard
	if ctx.EnvType != sysctx.EnvVagrant && ctx.EnvType != sysctx.EnvCI {
		os.RemoveAll(buildDir)
	}
}
