package builder

import (
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"time"

	sysctx "coa/pkg/context" // Il nostro scudo contestuale
)

// packAlpine costruisce il pacchetto per Alpine Linux (.apk)
// RISPETTA IL PATTO: Sfrutta il RuntimeContext per non usurare i dischi e isolare i build.
func packAlpine(pkgVersion string, ctx sysctx.RuntimeContext) {
	// Convenzione Alpine: nome-versione-revisione
	pkgName := fmt.Sprintf("oa-tools-%s-r0", pkgVersion)
	apkFile := fmt.Sprintf("%s.apk", pkgName)

	LogBuild("Iniziando il pacchettizzamento per Alpine Linux (musl/apk)...")

	// 1. Il tavolo da lavoro è la fucina sicura definita dal Contesto
	buildDir := filepath.Join(ctx.BaseBuildDir, pkgName)
	os.RemoveAll(buildDir)

	// 2. Creazione struttura directory standard (Niente cartella DEBIAN per Alpine)
	dirs := []string{
		filepath.Join(buildDir, "usr/bin"),
		filepath.Join(buildDir, "etc/oa-tools.d/brain.d"),
		filepath.Join(buildDir, "usr/share/man/man1"),
		filepath.Join(buildDir, "usr/share/bash-completion/completions"),
		filepath.Join(buildDir, "usr/share/zsh/vendor-completions"),
		filepath.Join(buildDir, "usr/share/fish/vendor_completions.d"),
	}
	for _, dir := range dirs {
		os.MkdirAll(dir, 0755)
	}

	// 3. Installazione binari prendendoli direttamente dalla fucina
	binPath := filepath.Join(buildDir, "usr/bin")
	copyFile(filepath.Join(ctx.BaseBuildDir, "oa", "oa"), filepath.Join(binPath, "oa"))
	copyFile(filepath.Join(ctx.BaseBuildDir, "coa", "coa"), filepath.Join(binPath, "coa"))
	os.Chmod(filepath.Join(binPath, "oa"), 0755)
	os.Chmod(filepath.Join(binPath, "coa"), 0755)

	// Creazione del symlink di legacy/compatibilità per 'eggs'
	os.Symlink("coa", filepath.Join(binPath, "eggs"))

	// 4. Gestione della Configurazione YAML
	confDest := filepath.Join(buildDir, "etc/oa-tools.d")
	brainDest := filepath.Join(confDest, "brain.d")

	oaYamlContent := fmt.Sprintf(`---
# oa-tools configuration
# coa is the mind and oa the arm
# Philosophy: https://penguins-eggs.net/blog/eggs-bananas

system:
  dialect: "oa"
  version: "%s"

wardrobe:
  root: "~/.oa-wardrobe"
  repo: "https://github.com/pieroproietti/oa-wardrobe.git"

remaster:
  default_user: "artisan"
  work_dir: "/home/eggs"
`, pkgVersion)

	os.WriteFile(filepath.Join(confDest, "oa-tools.yaml"), []byte(oaYamlContent), 0644)

	// Popolamento brain.d dai sorgenti stabili
	brainSrc := filepath.Join(ctx.CoaDir, "brain.d")
	exec.Command("sh", "-c", fmt.Sprintf("cp -r %s/* %s/", brainSrc, brainDest)).Run()

	// ---------------------------------------------------------
	// ORIGINE DOCUMENTI
	// ---------------------------------------------------------
	docSourceDir := filepath.Join(ctx.BaseBuildDir, "docs")

	// 5. Documentazione (Man pages)
	manDir := filepath.Join(buildDir, "usr/share/man/man1")
	exec.Command("sh", "-c", fmt.Sprintf("cp %s/man/*.1 %s/ && gzip -9 %s/*.1", docSourceDir, manDir, manDir)).Run()

	// 6. Completamenti shell e alias
	bashTarget := filepath.Join(buildDir, "usr/share/bash-completion/completions/coa")
	copyFile(filepath.Join(docSourceDir, "completion/coa.bash"), bashTarget)
	copyFile(filepath.Join(docSourceDir, "completion/coa.zsh"), filepath.Join(buildDir, "usr/share/zsh/vendor-completions/_coa"))
	copyFile(filepath.Join(docSourceDir, "completion/coa.fish"), filepath.Join(buildDir, "usr/share/fish/vendor_completions.d/coa.fish"))

	os.Symlink("coa", filepath.Join(buildDir, "usr/share/bash-completion/completions/eggs"))
	os.Symlink("_coa", filepath.Join(buildDir, "usr/share/zsh/vendor-completions/_eggs"))
	os.Symlink("coa.fish", filepath.Join(buildDir, "usr/share/fish/vendor_completions.d/eggs.fish"))

	f, err := os.OpenFile(bashTarget, os.O_APPEND|os.O_WRONLY, 0644)
	if err == nil {
		f.WriteString("\n# eggs alias completion support\ncomplete -o default -F __start_coa eggs\n")
		f.Close()
	}

	// 7. Generazione file .PKGINFO (La carta d'identità di Alpine)
	// Alpine richiede questo file esattamente nella radice dell'archivio tar.
	timestamp := time.Now().Unix()
	pkgInfoContent := fmt.Sprintf(`# Generated by oa-tools builder
pkgname = oa-tools
pkgver = %s-r0
pkgdesc = coa is the mind and oa the arm
url = https://penguins-eggs.net
builddate = %d
packager = Piero Proietti <piero.proietti@gmail.com>
arch = x86_64
depend = squashfs-tools xorriso dosfstools mtools rsync git sudo grub-efi
`, pkgVersion, timestamp)

	os.WriteFile(filepath.Join(buildDir, ".PKGINFO"), []byte(pkgInfoContent), 0644)

	// 8. Impacchettamento nativo: il rigoroso formato "v2" di Alpine!
	// Un file .apk è formato da DUE stream gzip concatenati l'uno all'altro.
	tmpApkLocation := filepath.Join(ctx.BaseBuildDir, apkFile)
	controlTar := filepath.Join(ctx.BaseBuildDir, "control.tar.gz")
	dataTar := filepath.Join(ctx.BaseBuildDir, "data.tar.gz")

	LogBuild("Forgiatura formato APK v2 (Control Stream + Data Stream)...")

	// Stream 1 (Controllo): Contiene ESCLUSIVAMENTE .PKGINFO
	cmdControl := exec.Command("tar", "-czf", controlTar, "-C", buildDir, ".PKGINFO")
	cmdControl.Stdout, cmdControl.Stderr = os.Stdout, os.Stderr
	if err := cmdControl.Run(); err != nil {
		LogError("Impossibile creare lo stream di controllo: %v", err)
		return
	}

	// Stream 2 (Dati): Contiene le cartelle di sistema (usr, etc)
	cmdData := exec.Command("tar", "-czf", dataTar, "-C", buildDir, "usr", "etc")
	cmdData.Stdout, cmdData.Stderr = os.Stdout, os.Stderr
	if err := cmdData.Run(); err != nil {
		LogError("Impossibile creare lo stream dei dati: %v", err)
		return
	}

	// Saldiamo i due stream insieme per formare il pacchetto definitivo
	cmdConcat := exec.Command("sh", "-c", fmt.Sprintf("cat %s %s > %s", controlTar, dataTar, tmpApkLocation))
	if err := cmdConcat.Run(); err != nil {
		LogError("Impossibile concatenare gli stream apk: %v", err)
		return
	}

	// Ripuliamo gli scarti di lavorazione
	os.Remove(controlTar)
	os.Remove(dataTar)

	// 9. Destinazione finale simmetrica guidata dal Contesto
	switch ctx.EnvType {
	case sysctx.EnvVagrant:
		LogBuild("[Vagrant Mode] Pacchetto Alpine protetto in RAM: %s", tmpApkLocation)
	case sysctx.EnvCI:
		LogBuild("[CI Mode] Pacchetto Alpine rilasciato nel workspace: %s", tmpApkLocation)
	default:
		// Host o VM nativa
		finalTarget := filepath.Join(ctx.ProjRoot, apkFile)

		if err := copyFile(tmpApkLocation, finalTarget); err == nil {
			os.Remove(tmpApkLocation)
			LogBuild("Pacchetto Alpine sfornato nella root del progetto: %s", finalTarget)
		} else {
			LogError("Impossibile copiare il pacchetto nella repo: %v", err)
		}
	}

	// Pulizia dello staging scompattato
	os.RemoveAll(buildDir)
}
