#!/bin/bash
# Rescapp make_common script
# Copyright (C) 2012,2013,2014,2015,2016 Adrian Gibanel Lopez
#
# Rescapp is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# Rescapp is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Rescapp.  If not, see <http://www.gnu.org/licenses/>.


# This script assumes apt-get install live-helper has been done
# This script assumes that the user has sudo permissions on lh build


set -x
set -v

# Fetch version from folder directory name
VERSION=`head -1 VERSION`

CORE_PACKAGES="live-tools user-setup sudo eject"

RESCATUX_RELEASE_DIR="$(pwd)/rescatux-release/rescatux-${VERSION}"

MIRROR_BOOTSTRAP="http://deb.debian.org/debian/"
MIRROR_CHROOT="http://deb.debian.org/debian/"
MIRROR_CHROOT_SECURITY="http://security.debian.org/debian-security/"
DEBIAN_MAIN_MIRROR="http://deb.debian.org/debian/"
RESCATUX_MIRROR="http://rescatux.sourceforge.net/repo/"

ARCH="i386"
DISTRIBUTION="buster" # Todo: Select with a switch
DISTRIBUTION_OPTION="-d ${DISTRIBUTION}"

ARCH_OPTION="-a ${ARCH}" # Todo: Select with a switch
RESCATUX_STR="rescatux"

RESCATUX_MEDIA_STR="${RESCATUX_STR}_${MEDIA_STR}"
BASE_FILENAME=${BASE_FILENAME-"${RESCATUX_MEDIA_STR}_${ARCH}_`echo ${LINUX_FLAVOURS} | sed s/' '/'-'/g`_`head -n 1 VERSION`"}
CURRENT_FOLDER=$PWD

TEMP_FOLDER="$(pwd)/live-build"
SKEL_FOLDER="config/includes.chroot/etc/skel"

CHROOT_SOURCES_FOLDER="config/archives"
STRETCH_CHROOT_CONFIG="config/archives/buster.list.chroot"
RESCATUX_CHROOT_CONFIG="config/archives/rescatux.list.chroot"
CHROOT_APT_CONFIG_FOLDER1="config/apt/"
APT_PREFERENCES1="config/apt/preferences"
CHROOT_APT_CONFIG_FOLDER2="config/archives/"
CHROOT_APT_CONFIG_FOLDER3="config/archives/"
CHROOT_APT_CONFIG_FOLDER4="config/archives/"
APT_PREFERENCES4="config/archives/buster.pref.chroot"
PACKAGES_CHROOT_FOLDER="config/packages.chroot"


CUSTOM_PACKAGES_LISTS_FOLDER="config/package-lists"

LIVE_HELPER_LISTS_FOLDER="/usr/share/live/build/lists"
RESCATUX_DATA_FOLDER="config/includes.chroot/usr/share/rescatux-data/"
RESCATUX_BIN_FOLDER="config/includes.chroot/usr/bin/"
RLE_FOLDER="config/binary_syslinux"
RLE_FILE="${RLE_FOLDER}/${RESCATUX_STR}.rle"

LB_ISO_APPLICATION="Rescatux Gnu/Linux ${VERSION}"
LB_ISO_PUBLISHER="Rescatux team"
LB_ISO_VOLUME="Rescatux${VERSION}"

RESCATUX_LOGOS_SRC="logos-src"
RESCATUX_LOGOS="logos"

RESCAPP_EXTRA_FOLDER="rescapp-extra"
RESCATUX_EXTRA_FOLDER="rescatux-extra"

if [ -e 'make_common.custom' ] ; then
  source make_common.custom
fi

mkdir --parents $TEMP_FOLDER/${RLE_FOLDER}
# Generate logo - Begin
cd ${RESCATUX_LOGOS_SRC}
sudo bash -c "./generate_logo.sh \"${RESCATUX_STR}\" \"${VERSION}\" \"${TEMP_FOLDER}/${RLE_FILE}\""
cd ..
# Generate logo - End

mkdir --parents $TEMP_FOLDER/


sudo rm -rf ${TEMP_FOLDER}/config
cp -a live-config ${TEMP_FOLDER}/config
mkdir --parents ${TEMP_FOLDER}/${PACKAGES_CHROOT_FOLDER}
mkdir --parents $TEMP_FOLDER/${CUSTOM_PACKAGES_LISTS_FOLDER}
mkdir --parents $TEMP_FOLDER/${RESCATUX_DATA_FOLDER}
mkdir --parents $TEMP_FOLDER/${RESCATUX_BIN_FOLDER}
mkdir --parents $TEMP_FOLDER/${SKEL_FOLDER}/Desktop/
cp ${RESCAPP_EXTRA_FOLDER}/rescapp.desktop $TEMP_FOLDER/${SKEL_FOLDER}/Desktop/rescapp.desktop
cp ${RESCAPP_EXTRA_FOLDER}/show-rescapp-logs.desktop $TEMP_FOLDER/${SKEL_FOLDER}/Desktop/
cp -r ${RESCATUX_LOGOS} $TEMP_FOLDER/${RESCATUX_DATA_FOLDER}
cp ${RESCATUX_EXTRA_FOLDER}/set-rescatux-background.sh $TEMP_FOLDER/${RESCATUX_BIN_FOLDER}
cp ${RESCATUX_EXTRA_FOLDER}/start-rescatux-tightvnc-server.sh $TEMP_FOLDER/${RESCATUX_BIN_FOLDER}
cp ${RESCATUX_EXTRA_FOLDER}/rescatux-startup-wizard.sh $TEMP_FOLDER/${RESCATUX_BIN_FOLDER}
for n_splash_dir in extlinux isolinux pxelinux syslinux ; do
  sed -i "s/@RESCATUX_VERSION@/${VERSION}/g" \
    ${TEMP_FOLDER}/config/bootloaders/${n_splash_dir}/splash.svg
done
cd $TEMP_FOLDER
sudo bash -c "echo \"${CORE_PACKAGES}\" > $TEMP_FOLDER/${CUSTOM_PACKAGES_LISTS_FOLDER}/recommends.list.chroot"
sudo bash -c "echo \"${PACKAGES}\" > $TEMP_FOLDER/${CUSTOM_PACKAGES_LISTS_FOLDER}/${RESCATUX_MEDIA_STR}.list.chroot"

mkdir --parents $TEMP_FOLDER/${CHROOT_SOURCES_FOLDER}
echo -e -n "deb ${DEBIAN_MAIN_MIRROR} buster main" > $TEMP_FOLDER/${STRETCH_CHROOT_CONFIG}
echo -e -n "deb ${RESCATUX_MIRROR} buster-dev main\n" > $TEMP_FOLDER/${RESCATUX_CHROOT_CONFIG}
echo -e -n "deb ${RESCATUX_MIRROR} buster-live-boot-dev main" >> $TEMP_FOLDER/${RESCATUX_CHROOT_CONFIG}

mkdir --parents $TEMP_FOLDER/${CHROOT_APT_CONFIG_FOLDER1}
mkdir --parents $TEMP_FOLDER/${CHROOT_APT_CONFIG_FOLDER2}
mkdir --parents $TEMP_FOLDER/${CHROOT_APT_CONFIG_FOLDER3}
mkdir --parents $TEMP_FOLDER/${CHROOT_APT_CONFIG_FOLDER4}

tee $TEMP_FOLDER/${APT_PREFERENCES1} \
 <<END

END

#tee $TEMP_FOLDER/${APT_PREFERENCES2} \
# <<END
#
#END

#tee $TEMP_FOLDER/${APT_PREFERENCES3} \
# <<END
#
#END

tee $TEMP_FOLDER/${APT_PREFERENCES4} \
 <<END

END

# Initial lb config
if [ ! -d .build ] ; then
  lb config
  # Copy auto examples
  cp /usr/share/doc/live-build/examples/auto/* auto/
fi

# Generate auto/config
cat << EOF > auto/config
#!/bin/sh

lb config noauto \\
  --bootloaders "${BOOTLOADERS_OPTION}" \\
  --updates false \\
  --apt-recommends false \\
  --linux-flavours "${LINUX_FLAVOURS}" \\
  ${DISTRIBUTION_OPTION} \\
  ${ARCH_OPTION} \\
  ${CHROOT_FILESYSTEM_OPTION} \\
  ${CACHE_STAGES_OPTION} \\
  ${BOOT_OPTION} \\
  --mirror-bootstrap "${MIRROR_BOOTSTRAP}" \\
  --mirror-chroot "${MIRROR_CHROOT}" \\
  --mirror-chroot-security "${MIRROR_CHROOT_SECURITY}" \\
  --apt-options "--force-yes --yes -o Acquire::Check-Valid-Until=false -o Acquire::AllowInsecureRepositories=true -o Acquire::AllowDowngradeToInsecureRepositories=true" \\
  --iso-application "${LB_ISO_APPLICATION}" \\
  --iso-publisher "${LB_ISO_PUBLISHER}" \\
  --iso-volume "${LB_ISO_VOLUME}" \\
  ${RESCATUX_LIVE_CONFIG_SOURCE_OPTIONS} \\
  --bootappend-live "boot=live config quiet splash locales=en_US.UTF-8" \\
  --selinux permissive \\
        "\${@}"
EOF

sudo bash -c "lb config"
sudo bash -c "lb clean"

if [ ! -d "${RESCATUX_RELEASE_DIR}" ] ; then
  mkdir --parents "${RESCATUX_RELEASE_DIR}"
fi

sudo bash -c "lb build 2>&1 | tee ${RESCATUX_RELEASE_DIR}/${BASE_FILENAME}_build.log"
mv live-image-i386${IS_HYBRID}.${FILE_EXTENSION} ${RESCATUX_RELEASE_DIR}/${BASE_FILENAME}.${FILE_EXTENSION}
mv live-image-i386.packages ${RESCATUX_RELEASE_DIR}/${BASE_FILENAME}.packages
if [ "x${RESCATUX_LIVE_CONFIG_SOURCE_OPTIONS}" != "x" ] ; then
  if [ ! -d "${RESCATUX_RELEASE_DIR}/source-code" ] ; then
    mkdir --parents "${RESCATUX_RELEASE_DIR}/source-code"
  fi
  mv live-image-source.debian.tar ${RESCATUX_RELEASE_DIR}/source-code/${BASE_FILENAME}-source.debian.tar
  mv live-image-source.live.tar ${RESCATUX_RELEASE_DIR}/source-code/${BASE_FILENAME}-source.live.tar
fi
cd ${RESCATUX_RELEASE_DIR}
md5sum ${BASE_FILENAME}.${FILE_EXTENSION} > ${BASE_FILENAME}.${FILE_EXTENSION}.md5
echo "${BASE_FILENAME}.${FILE_EXTENSION} (and md5sum) DONE!"
cd ${CURRENT_FOLDER}

if [ "x${RESCATUX_LIVE_CONFIG_SOURCE_OPTIONS}" != "x" ] ; then
  ./make-source-code-aux.sh
fi
