#!/bin/bash
# rescatux_common_packages
# Copyright (C) 2014,2015,2016 Adrian Gibanel Lopez
#
# Rescatux is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# Rescapp is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Rescapp.  If not, see <http://www.gnu.org/licenses/>.

# This script assumes apt-get install live-helper has been done
# This script assumes that the user has sudo permissions on lh build

RESCAPP_PACKAGES="rescapp"
DESKTOP_METAPACKAGE="task-desktop"

# Remove non needed LXQT packages
LXQT_REMOVE_PACKAGES="\
lxqt-theme-debian- \
"

# Replaces Debian lxqt metapackage
# Current buster package installs
# too many unneeded packages

LXQT_META_PACKAGE="\
featherpad \
lximage-qt \
lxqt-core \
qterminal \
qttranslations5-l10n \
xarchiver \
xfwm4 \
"

LXQT_ADDITIONAL_PACKAGES="\
 cmst \
 faenza-icon-theme
"
SYNAPTIC_PACKAGES="synaptic"

GDDRESCUE_PACKAGES="gddrescue"
MYRESCUE_PACKAGES="myrescue"

TIGHTVNCSERVER_PACKAGES="x11vnc psmisc"

TESTDISK_PACKAGES="testdisk"
GPARTED_PACKAGES="gparted gpart"

OPTIONAL_RESCAPP_DEPENDENCIES="\
  ${TESTDISK_PACKAGES} \
  ${GPARTED_PACKAGES} \
"

XORG_EXTRA_PACKAGES="\
 xserver-xorg-input-wacom \
 xserver-xorg-legacy \
 xserver-xorg-video-intel \
 xserver-xorg-video-qxl \
"

COMMON_PACKAGES="\
 ${SYNAPTIC_PACKAGES} \
 ${GDDRESCUE_PACKAGES} \
 ${MYRESCUE_PACKAGES} \
 ${RESCAPP_PACKAGES} \
 ${DESKTOP_METAPACKAGE} \
 ${LXQT_META_PACKAGE} \
 ${LXQT_ADDITIONAL_PACKAGES} \
 ${LXQT_REMOVE_PACKAGES} \
 ${TIGHTVNCSERVER_PACKAGES} \
 ${OPTIONAL_RESCAPP_DEPENDENCIES} \
 ${XORG_EXTRA_PACKAGES} \
 firefox-esr \
 syslinux \
 gawk\
 extundelete\
 locales \
 ca-certificates \
 wmctrl \
 xterm \
 " # I add syslinux so that isohybrid command is recognised.
