#!/bin/bash
# Rescapp Fsck run script
# Copyright (C) 2012,2013,2014,2015,2016,2017,2018,2019,2020 Adrian Gibanel Lopez
#
# Rescapp is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# Rescapp is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Rescapp.  If not, see <http://www.gnu.org/licenses/>.

source ${RESCAPP_LIB_FILE}

set -x
set -v


# fsck Main program

UEFIREINSTALLMICROSOFT_OK_STR="The reinstallation, of the Microsoft Windows UEFI boot entries was OK ! :)"
UEFIREINSTALLMICROSOFT_KO_STR="The reinstallation, of the Microsoft Windows UEFI boot entries was not ok :("
UEFIREINSTALLMICROSOFT_RUNNING_STR="Reinstalling Microsoft Windows UEFI boot entries"
UEFIREINSTALLMICROSOFT_WINDOWS_PARTITIONS_NOT_FOUND="No Windows partitions were found or chosen."
UEFIREINSTALLMICROSOFT_EFI_PARTITIONS_NOT_FOUND="No EFI partitions were found or chosen."
UEFIREINSTALLMICROSOFT_BACKUP_WENT_WRONG="Backup of EFI directory went wrong."


SELECTED_EFI_PARTITION="$(rtux_Choose_EFI_System_partition)"
if [ "x${SELECTED_EFI_PARTITION}" != "x" ] ; then
  SELECTED_WINDOWS_PARTITION=$(rtux_Choose_Windows_partition);
  if [ "x${SELECTED_WINDOWS_PARTITION}" != "x" ] ; then
    if rtux_backup_efi_partition "${SELECTED_EFI_PARTITION}" ; then
      if rtux_Run_Show_Progress "${UEFIREINSTALLMICROSOFT_RUNNING_STR}" rtux_UEFI_Reinstall_Microsoft_Boot_Entries "${SELECTED_EFI_PARTITION}" "${SELECTED_WINDOWS_PARTITION}";
      then
        rtux_Message_Success ${UEFIREINSTALLMICROSOFT_OK_STR}
      else
        rtux_Message_Failure ${UEFIREINSTALLMICROSOFT_KO_STR}
      fi
    else
      rtux_Message_Warning ${UEFIREINSTALLMICROSOFT_BACKUP_WENT_WRONG}
      rtux_Message_Failure ${UEFIREINSTALLMICROSOFT_KO_STR}
    fi
  else
    rtux_Message_Warning ${UEFIREINSTALLMICROSOFT_WINDOWS_PARTITIONS_NOT_FOUND}
    rtux_Message_Failure ${UEFIREINSTALLMICROSOFT_KO_STR}
  fi
else
  rtux_Message_Warning ${UEFIREINSTALLMICROSOFT_EFI_PARTITIONS_NOT_FOUND}
  rtux_Message_Failure ${UEFIREINSTALLMICROSOFT_KO_STR}
fi



