name: 10004-almalinux9-container-test

on:
  push:
  workflow_dispatch:

jobs:
  build:
    name: 10004-almalinux9-container-test
    runs-on: ubuntu-24.04
    timeout-minutes: 7200
    steps:
      - name: Check Out Repo 
        uses: actions/checkout@v4
      - name: Use Node.js 18
        uses: actions/setup-node@v2
        with:
          node-version: 18.x
      - name: run 10004-almalinux9-container-test.sh
        run: |
          ./10004-almalinux9-container-test.sh
      
