## WARNING WHEN CHANGING CI FILES

### 1. don't change ci files if you are not sure
### 2. don't change ci files if it is not necessary
### 3. don't disable any one of ci tests
### 4. don't change the current workflow of build iso
### 5. don't change the number of ci files, just add new files with a new number range such as 30000- 40000 50000
### 6. if you want to use penguins-wardroe to build,add new ci tests and don't change the current ci files and workflows

name: 20005-devuan5

on:
  # push:
  workflow_dispatch:

jobs:
  build:
    name: 20005 Devuan 5 build system
    runs-on: ubuntu-24.04
    timeout-minutes: 7200
    steps:
      - name: Check Out Repo 
        uses: actions/checkout@v4
      - name: Setup nodejs 18
        uses: actions/setup-node@v2
        with:
          node-version: 18.x
      - name: ISO build
        run: |
          ./20005-devuan5-container-test.sh
      - name: ISO export
        uses: actions/upload-artifact@v4
        with:
          name: egg-of_devuan-daedalus-minimal_amd64_latest
          path: ./mychroot/ci/iso/egg-of*.iso
          retention-days: 1
          if-no-files-found: warn
          compression-level: 0
          overwrite: true
          include-hidden-files: false          
      
