name: 101-ubuntu-latest

# only manual, thanks
on:
  push:
    branches: [ "main", "devel" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch: # Fondamentale: ti permette di lanciarlo a mano se serve

jobs:
  build:

    runs-on: ubuntu-slim
    timeout-minutes: 120

    steps:
    - uses: actions/checkout@v6

    - name: run buidl and test
      run: |
        ./tests/101-ubuntu-latest/1001.ubuntu.latest.build.test.sh

