name: 105-vagrant-arch-linux

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest
    timeout-minutes: 120

    steps:
    - uses: actions/checkout@v6

    - name: run buidl and test
      run: |
        ./tests/105-vagrant-arch-linux/vagrant.install.build.test.sh

