name: 101-ubuntu-latest

# only manual, thanks
on:
  push:
    branches: [ "main", "devel" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest
    timeout-minutes: 120

    steps:
    - uses: actions/checkout@v6

    - name: full smoke-test on CI 
      run: |
        ./tests/101-ubuntu-latest/1001.ubuntu.latest.build.test.sh

