name: 111-vagrant-ubuntu-26.04

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: run buidl and test
      run: |
        ./tests/111-vagrant-ubuntu-26.04/vagrant.install.build.test.sh

