name: 102-vagrant-template

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: run buidl and test
      run: |
        ./tests/102-vagrant-template/vagrant.install.build.test.sh

