name: 111-vagrant-ubuntu-26.04

on: 
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest
    timeout-minutes: 120

    steps:
    - uses: actions/checkout@v6

    - name: run buidl and test
      run: |
        ./tests/111-vagrant-ubuntu-26.04/vagrant.install.build.test.sh

