name: 105-vagrant-arch-linux

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: run buidl and test
      run: |
        ./tests/105-vagrant-arch-linux/vagrant.install.build.test.sh

