name: 104-vagrant-alpine-3.23

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    timeout-minutes: 120

    steps:
    - uses: actions/checkout@v6

    - name: run buidl and test
      run: |
        ./tests/104-vagrant-alpine-3.23/vagrant.install.build.test.sh

