name: 106-vagrant-centos-10-stream

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: run buidl and test
      run: |
        ./tests/106-vagrant-centos-10-stream/vagrant.install.build.test.sh

