name: 3001-ubuntu-latest-py

# only manual, thanks
on:
  push:
    branches: [ "main", "devel" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch: # Fondamentale: ti permette di lanciarlo a mano se serve


jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 120

    steps:
    - uses: actions/checkout@v6

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Run Python replacement smoke tests
      run: |
        chmod +x ./tests/3001-py/3001.py.test.sh
        ./tests/3001-py/3001.py.test.sh
