name: CI Matrix

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        distro: [arch, debian]
    
    steps:
    - uses: actions/checkout@v6

    - name: Prepara ambiente (Vagrant & Libvirt)
      run: |
        # 1. Aggiorna i repository
        sudo apt-get update
        # 2. Installa solo le dipendenze di compilazione (niente installazione manuale di vagrant)
        sudo apt-get install -y qemu-kvm libvirt-daemon-system libvirt-clients bridge-utils libvirt-dev build-essential ruby-dev
        
        # 3. Usa il vagrant già presente nel runner (è più stabile)
        # 4. Installa il plugin (questo scarica i binari se disponibili, risparmiando tempo)
        vagrant plugin install vagrant-libvirt

    - name: Build e Test
      run: |
        newgrp libvirt <<EOF
          ./github-ci-roots/${{ matrix.distro }}/do-${{ matrix.distro }}.sh
        EOF

    - name: Recupera uovo
      run: |
        newgrp libvirt <<EOF
          vagrant ssh ${{ matrix.distro }} -c "cat ~/*.iso" > ./github-ci-roots/${{ matrix.distro }}/egg-of-${{ matrix.distro }}.iso
        EOF

    - name: Salva artefatto
      uses: actions/upload-artifact@v4
      with:
        name: ${{ matrix.distro }}-egg
        path: ./github-ci-roots/${{ matrix.distro }}/*.iso
        retention-days: 5