name: CI Matrix

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    # Usiamo un'immagine che ha già vagrant e libvirt pronti
    container:
      image: ghcr.io/vagrant-libvirt/vagrant-libvirt:latest
      options: --privileged # Necessario per KVM/Libvirt
    
    strategy:
      matrix:
        distro: [arch, debian]
    
    steps:
    - uses: actions/checkout@v6

    - name: Build e Test
      run: |
        /usr/bin/vagrant up ${{ matrix.distro }} --provider=libvirt
        ./github-ci-roots/${{ matrix.distro }}/do-${{ matrix.distro }}.sh

    - name: Estrazione ISO
      if: always() # Esegue anche se lo step precedente avesse fallito
      run: |
        # Usiamo il cat per bypassare i permessi 9p
        /usr/bin/vagrant ssh ${{ matrix.distro }} -c "cat ~/egg.iso" > ./github-ci-roots/${{ matrix.distro }}/egg-of-${{ matrix.distro }}.iso

    - name: Salva artefatto
      uses: actions/upload-artifact@v4
      with:
        name: ${{ matrix.distro }}-egg
        path: ./github-ci-roots/${{ matrix.distro }}/*.iso
        retention-days: 5        