name: debian

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 120

    steps:
    - uses: actions/checkout@v6

    - name: Prepara l'ambiente (Vagrant & Libvirt)
      run: |
        sudo apt-get update
        sudo apt-get install -y wget qemu-kvm libvirt-daemon-system libvirt-clients bridge-utils libvirt-dev
        wget -q https://releases.hashicorp.com/vagrant/2.4.9/vagrant_2.4.9-1_amd64.deb
        sudo dpkg -i vagrant_2.4.9-1_amd64.deb
        vagrant plugin install vagrant-libvirt

    - name: Esegui Build e Test
      run: |
        ./github-ci-roots/debian/do-debian.sh

    - name: Recupera la ISO dalla VM
      run: |
        # Ora il runner sa cosa è vagrant e lo usa come un cecchino
        vagrant ssh default -c "cat ~/*.iso" > ./github-ci-roots/debian/egg-of-debian.iso

    - name: Salva la ISO generata come artefatto
      uses: actions/upload-artifact@v4
      with:
        name: debian-13-egg
        path: ./github-ci-roots/debian/*.iso
        retention-days: 5
        