name: debian

on: 
  #push:
  #  branches: [ main ]
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest
    timeout-minutes: 120

    steps:
    - uses: actions/checkout@v6

    - name: run buidl and test
      run: |
        ./_tests/debian/do-debian.sh

    - name: Salva la ISO generata come artefatto
      uses: actions/upload-artifact@v4
      with:
        name: debian-13-egg
        # Il percorso host dove lo script Bash ha depositato la ISO
        path: ./_tests/debian/*.iso
        # Mantieni il file sui server per 5 giorni per evitare di sprecare spazio inutile
        retention-days: 5

