name: Fornaces - ISO Build

on:
  # Permette di far partire la pipeline manualmente dal tab "Actions" di GitHub
  workflow_dispatch: 
  
  # Decommenta queste righe se vuoi che parta in automatico ad ogni nuova release
  # release:
  #   types: [published]

jobs:
  bake-isos:
    # Il tassello fondamentale: dice a GitHub di dirottare il job sul tuo server locale!
    runs-on: self-hosted 

    steps:
      - name: Checkout del codice
        uses: actions/checkout@v4

      - name: Rendi eseguibile lo script
        run: chmod +x bin/furnace.sh

      - name: 🔥 Avvio della Fornace
        # Esegue lo script con privilegi di root per poter comandare Proxmox (qm)
        run: sudo bin/furnace.sh